use std::collections::VecDeque;
use std::env;
use std::fs::{self, File};
use std::io::Write;
use std::path::{Path, PathBuf};

use image::{Rgba, RgbaImage};

#[allow(dead_code)]
#[path = "src/key_geometry.rs"]
mod key_geometry;

const TRACK_COLORS: [[u8; 3]; 8] = [
    [0x4F, 0xC3, 0xF7],
    [0xFF, 0xB7, 0x4D],
    [0xA5, 0xD6, 0xA7],
    [0xF4, 0x8F, 0xB1],
    [0xCE, 0x93, 0xD8],
    [0xFF, 0xF1, 0x76],
    [0xFF, 0x8A, 0x65],
    [0x80, 0xCB, 0xC4],
];

#[derive(Clone, Copy)]
enum KeyGroup {
    Alpha,
    Nav,
    Arrow,
    Numpad,
}

#[derive(Clone, Copy)]
struct SpriteSpec {
    id: u32,
    source: usize,
    column: f32,
    row: f32,
    width: f32,
    height: f32,
    columns: f32,
    rows: f32,
    group: KeyGroup,
}

fn main() {
    let asset_dir = PathBuf::from("assets/keyboard");
    let source_names = [
        "top row.png",
        "2nd row.png",
        "3rd row.png",
        "4 row.png",
        "bottom row.png",
        "home.png",
        "arrow keys.png",
        "numpad.png",
    ];
    for name in source_names {
        println!("cargo:rerun-if-changed={}", asset_dir.join(name).display());
    }
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/key_geometry.rs");

    let sources: Vec<RgbaImage> = source_names
        .iter()
        .map(|name| {
            image::open(asset_dir.join(name))
                .unwrap_or_else(|error| panic!("could not open {name}: {error}"))
                .into_rgba8()
        })
        .collect();
    let specs = sprite_specs();
    assert_eq!(specs.len(), 100);

    let output_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR must be set"));
    let sprite_dir = output_dir.join("k2-key-sprites");
    fs::create_dir_all(&sprite_dir).expect("could not create key sprite output directory");

    let mut generated = String::from(
        "// Generated by build.rs. Pixel isolation and colour replacement happen at build time.\n\
         static PREPROCESSED_KEY_SPRITES: [[&[u8]; 11]; 100] = [\n",
    );

    for spec in &specs {
        let source = &sources[spec.source];
        let crop = source_crop(*spec, source);
        let mut resting =
            image::imageops::crop_imm(source, crop.0, crop.1, crop.2, crop.3).to_image();
        isolate_key(&mut resting);

        generated.push_str("    [\n");
        for variant in 0..11 {
            let mut pixels = resting.clone();
            if let Some(color) = variant_color(*spec, variant) {
                recolor_key(&mut pixels, color, *spec);
            }
            let file_name = format!("key-{}-{variant}.webp", spec.id);
            write_webp(&sprite_dir.join(&file_name), &pixels);
            generated.push_str(&format!(
                "        include_bytes!(concat!(env!(\"OUT_DIR\"), \"/k2-key-sprites/{file_name}\")),\n"
            ));
        }
        generated.push_str("    ],\n");
    }
    generated.push_str(
        "];\n\
         fn preprocessed_key_sprite(key_id: u32, variant: u8) -> Option<&'static [u8]> {\n\
             let key = key_id.checked_sub(14)? as usize;\n\
             PREPROCESSED_KEY_SPRITES.get(key)?.get(variant as usize).copied()\n\
         }\n",
    );
    let mut manifest = File::create(output_dir.join("k2_key_sprites.rs"))
        .expect("could not create generated key sprite manifest");
    manifest
        .write_all(generated.as_bytes())
        .expect("could not write generated key sprite manifest");
}

fn sprite_specs() -> Vec<SpriteSpec> {
    let mut specs = Vec::with_capacity(100);
    let mut id = 14_u32;
    let mut push = |source, column, row, width, height, columns, rows, group| {
        specs.push(SpriteSpec {
            id,
            source,
            column,
            row,
            width,
            height,
            columns,
            rows,
            group,
        });
        id += 1;
    };

    for source in [0_usize, 2] {
        push(source, 0.0, 0.0, 1.5, 1.0, 15.0, 1.0, KeyGroup::Alpha);
        for column in 1..14 {
            push(
                source,
                0.5 + column as f32,
                0.0,
                if column == 13 { 1.5 } else { 1.0 },
                1.0,
                15.0,
                1.0,
                KeyGroup::Alpha,
            );
        }
        if source == 0 {
            for column in 0..15 {
                push(1, column as f32, 0.0, 1.0, 1.0, 15.0, 1.0, KeyGroup::Alpha);
            }
        }
    }
    for column in 0..15 {
        push(3, column as f32, 0.0, 1.0, 1.0, 15.0, 1.0, KeyGroup::Alpha);
    }
    push(4, 0.0, 0.0, 1.5, 1.0, 15.0, 1.0, KeyGroup::Alpha);
    for column in 1..11 {
        push(
            4,
            1.5 + column as f32,
            0.0,
            1.0,
            1.0,
            15.0,
            1.0,
            KeyGroup::Alpha,
        );
    }
    push(4, 13.5, 0.0, 1.5, 1.0, 15.0, 1.0, KeyGroup::Alpha);

    for row in 0..2 {
        for column in 0..3 {
            push(
                5,
                column as f32,
                row as f32,
                1.0,
                1.0,
                3.0,
                2.0,
                KeyGroup::Nav,
            );
        }
    }
    for (column, row) in [(1.0, 0.0), (0.0, 1.0), (1.0, 1.0), (2.0, 1.0)] {
        push(6, column, row, 1.0, 1.0, 3.0, 2.0, KeyGroup::Arrow);
    }
    for row in 0..5 {
        for column in 0..4 {
            push(
                7,
                column as f32,
                row as f32,
                1.0,
                1.0,
                4.0,
                5.0,
                KeyGroup::Numpad,
            );
        }
    }

    assert_eq!(id, 114);
    specs
}

fn source_crop(spec: SpriteSpec, source: &RgbaImage) -> (u32, u32, u32, u32) {
    if matches!(spec.group, KeyGroup::Alpha) {
        let rect = key_geometry::alpha_key_source_rect(spec.source + 1, spec.column, spec.width);
        return (
            rect.x.round() as u32,
            rect.y.round() as u32,
            rect.width.round() as u32,
            rect.height.round() as u32,
        );
    }
    let x0 = (spec.column / spec.columns * source.width() as f32).round() as u32;
    let y0 = (spec.row / spec.rows * source.height() as f32).round() as u32;
    let x1 = ((spec.column + spec.width) / spec.columns * source.width() as f32).round() as u32;
    let y1 = ((spec.row + spec.height) / spec.rows * source.height() as f32).round() as u32;
    (x0, y0, x1.saturating_sub(x0), y1.saturating_sub(y0))
}

fn luminance(pixel: &Rgba<u8>) -> f32 {
    (pixel[0] as f32 * 0.2126 + pixel[1] as f32 * 0.7152 + pixel[2] as f32 * 0.0722) / 255.0
}

fn isolate_key(image: &mut RgbaImage) {
    let width = image.width() as usize;
    let height = image.height() as usize;
    let eligible = |x: usize, y: usize| {
        let pixel = image.get_pixel(x as u32, y as u32);
        pixel[3] > 24 && luminance(pixel) > 0.20
    };
    let search_x = (width * 30 / 100)..(width * 75 / 100).max(1);
    let search_y = (height * 22 / 100)..(height * 68 / 100).max(1);
    let seed = search_y
        .flat_map(|y| search_x.clone().map(move |x| (x, y)))
        .filter(|&(x, y)| eligible(x, y))
        .max_by(|&(ax, ay), &(bx, by)| {
            luminance(image.get_pixel(ax as u32, ay as u32))
                .total_cmp(&luminance(image.get_pixel(bx as u32, by as u32)))
        })
        .expect("every extracted key cell must contain a keycap");

    // A nominal cell can contain the projecting side bevel of its neighbour.
    // Find the nearest dark vertical valley around the target's center and
    // prohibit the flood fill from crossing it. This removes the detached
    // coloured sliver without shaving the target key's own outer bevel.
    let band_y = (height * 8 / 100)..(height * 92 / 100).max(1);
    let sparse_limit = (height / 18).max(2);
    let column_counts: Vec<usize> = (0..width)
        .map(|x| {
            band_y
                .clone()
                .filter(|&y| {
                    let pixel = image.get_pixel(x as u32, y as u32);
                    pixel[3] > 24 && luminance(pixel) > 0.28
                })
                .count()
        })
        .collect();
    let left = (0..seed.0)
        .rev()
        .find(|&x| column_counts[x] <= sparse_limit)
        .map_or(0, |x| x + 1);
    let right = ((seed.0 + 1)..width)
        .find(|&x| column_counts[x] <= sparse_limit)
        .unwrap_or(width);

    let mut connected = vec![false; width * height];
    let mut queue = VecDeque::from([seed]);
    connected[seed.1 * width + seed.0] = true;
    while let Some((x, y)) = queue.pop_front() {
        for (next_x, next_y) in [
            (x.wrapping_sub(1), y),
            (x + 1, y),
            (x, y.wrapping_sub(1)),
            (x, y + 1),
        ] {
            if next_x < left || next_x >= right || next_y >= height {
                continue;
            }
            let index = next_y * width + next_x;
            if !connected[index] && eligible(next_x, next_y) {
                connected[index] = true;
                queue.push_back((next_x, next_y));
            }
        }
    }
    for _ in 0..3 {
        let previous = connected.clone();
        for y in 0..height {
            for x in left..right {
                let index = y * width + x;
                if previous[index] {
                    continue;
                }
                let touches = (x > left && previous[index - 1])
                    || (x + 1 < right && previous[index + 1])
                    || (y > 0 && previous[index - width])
                    || (y + 1 < height && previous[index + width]);
                if touches && image.get_pixel(x as u32, y as u32)[3] > 24 {
                    connected[index] = true;
                }
            }
        }
    }
    for (x, y, pixel) in image.enumerate_pixels_mut() {
        if !connected[y as usize * width + x as usize] {
            pixel[3] = 0;
        }
    }
}

fn variant_color(spec: SpriteSpec, variant: usize) -> Option<[u8; 3]> {
    match variant {
        0 => None,
        1..=8 => Some(TRACK_COLORS[variant - 1]),
        9 => Some(match spec.group {
            KeyGroup::Alpha => [0xFF, 0xA3, 0x55],
            KeyGroup::Nav => [0xFF, 0xB4, 0x58],
            KeyGroup::Arrow => [0xFF, 0x4C, 0x82],
            KeyGroup::Numpad => [0x50, 0xD4, 0xC8],
        }),
        10 => Some([0xFF, 0x3D, 0x72]),
        _ => unreachable!(),
    }
}

fn recolor_key(image: &mut RgbaImage, color: [u8; 3], spec: SpriteSpec) {
    let pixel_height = image.height().max(1) as f32;
    // The older equal-grid crops could contain a projecting sliver from the
    // previous key, so their left edge stays in its resting colour. Annotated
    // rows end exactly at the marked separator and contain the target key's
    // own bevel; preserving that edge causes the obvious cyan strip seen on
    // highlighted middle keys.
    let annotated_alpha = matches!(spec.group, KeyGroup::Alpha)
        && key_geometry::has_annotated_boundaries(spec.source + 1);
    let untouched_bevel = if matches!(spec.group, KeyGroup::Alpha)
        && !annotated_alpha
        && spec.column > 0.0
    {
        ((image.width() as f32 / spec.width) * 0.20).round() as u32
    } else {
        0
    };
    for (x, y, pixel) in image.enumerate_pixels_mut() {
        if pixel[3] == 0 {
            continue;
        }
        if x < untouched_bevel {
            continue;
        }
        let original = [pixel[0] as f32, pixel[1] as f32, pixel[2] as f32];
        let luminance =
            (original[0] * 0.2126 + original[1] * 0.7152 + original[2] * 0.0722) / 255.0;
        let material = ((luminance - 0.075) / 0.38).clamp(0.0, 1.0);
        let mix = 0.82 * material;
        let shade = (0.28 + luminance * 0.94).clamp(0.0, 1.08);
        let vertical = y as f32 / pixel_height;
        let press_shade = if vertical < 0.28 {
            0.72 + vertical / 0.28 * 0.28
        } else {
            1.0
        };
        for (channel, target) in color.into_iter().enumerate() {
            let colourized = target as f32 * shade;
            pixel[channel] = (original[channel] * (1.0 - mix) + colourized * mix)
                .mul_add(press_shade, 0.0)
                .clamp(0.0, 255.0) as u8;
        }
    }
}

fn write_webp(path: &Path, image: &RgbaImage) {
    let encoded =
        webp::Encoder::from_rgba(image.as_raw(), image.width(), image.height()).encode(82.0);
    fs::write(path, encoded.as_ref()).unwrap_or_else(|error| {
        panic!(
            "could not write preprocessed sprite {}: {error}",
            path.display()
        )
    });
}
