use std::cell::RefCell;
use std::collections::{HashMap, HashSet};

use iced::alignment::{Horizontal, Vertical};
use iced::widget::canvas::{self, Frame, Geometry, Path, Text};
use iced::{Color, Point, Rectangle, Renderer, Size, Theme, mouse, touch};

use crate::Message;
use crate::key::{Cluster, Key, KeyId};
use crate::key_geometry::{self, SourceRect, TextGuide};

include!(concat!(env!("OUT_DIR"), "/k2_key_sprites.rs"));

/// Embedded photographic pieces of the real K2. Keeping the handles alive in
/// `App` lets iced cache the decoded shell PNGs and generated key WebPs instead
/// of allocating them on every frame.
pub struct PhotoBoardAssets {
    pub shell: iced::widget::image::Handle,
    pub leds: iced::widget::image::Handle,
    /// Shared control-surface knob face (see
    /// `assets/keyboard/controls/README.md`) — the same physical-hardware
    /// asset family used for the mixer's CH/OCT knobs, reused here so the
    /// board's own 13 parameter knobs read as the same manufactured part.
    knob_face: iced::widget::image::Handle,
    key_sprites: RefCell<HashMap<(KeyId, u8, bool), iced::widget::image::Handle>>,
}

impl PhotoBoardAssets {
    pub fn new() -> Self {
        let handle = |bytes: &'static [u8]| iced::widget::image::Handle::from_bytes(bytes);
        Self {
            shell: handle(&include_bytes!("../assets/keyboard/keyboard-clean-mask.png")[..]),
            leds: handle(&include_bytes!("../assets/keyboard/led-panel-board-crop.png")[..]),
            // Downscaled once from the shared 1024px master, matching
            // `decode_and_downscale`'s use for the mixer knobs — these dials
            // render at well under 100px, and handing the GPU that much
            // minification directly risks the same mip-sampling artifacts
            // seen there.
            knob_face: crate::decode_and_downscale(
                &include_bytes!("../assets/keyboard/controls/rotary-knob-face.png")[..],
                128,
                128,
            ),
            key_sprites: RefCell::new(HashMap::new()),
        }
    }

    /// Selects an already-isolated, already-colourized WebP generated by
    /// `build.rs`. Runtime work is limited to creating and caching the image
    /// handle; no flood fill or per-pixel colour math can interrupt playback.
    fn key_sprite(
        &self,
        key: &Key,
        lit_track: Option<usize>,
        blank_numpad: bool,
    ) -> Option<iced::widget::image::Handle> {
        let variant = match lit_track {
            None => 0,
            Some(value) if value == usize::MAX - 1 => 10,
            Some(usize::MAX) => 9,
            Some(track) => 1 + (track % TRACK_COLORS.len()) as u8,
        };
        let blank_numpad = blank_numpad && matches!(key.cluster, Cluster::Numpad);
        if let Some(handle) = self
            .key_sprites
            .borrow()
            .get(&(key.id, variant, blank_numpad))
            .cloned()
        {
            return Some(handle);
        }
        let bytes = if blank_numpad {
            preprocessed_drum_key_sprite(key.id.0, variant)?
        } else {
            preprocessed_key_sprite(key.id.0, variant)?
        };
        let handle = iced::widget::image::Handle::from_bytes(bytes);
        self.key_sprites
            .borrow_mut()
            .insert((key.id, variant, blank_numpad), handle.clone());
        Some(handle)
    }
}

/// Per-track highlight palette — cycled for files with more than 8 tracks.
/// RGB values tuned for visibility on the dark PCB and dark staff background.
pub const TRACK_COLORS: &[(u8, u8, u8)] = &[
    (0x4F, 0xC3, 0xF7), // sky blue
    (0xFF, 0xB7, 0x4D), // amber
    (0xA5, 0xD6, 0xA7), // green
    (0xF4, 0x8F, 0xB1), // pink
    (0xCE, 0x93, 0xD8), // lavender
    (0xFF, 0xF1, 0x76), // yellow
    (0xFF, 0x8A, 0x65), // coral
    (0x80, 0xCB, 0xC4), // teal
];

pub(crate) const CANVAS_FONT: iced::Font = iced::Font::with_name("Fira Sans");
const TAPE_FONT: iced::Font = iced::Font::with_name("Permanent Marker");
#[cfg(test)]
const BASE_BOARD_HEIGHT: f32 = 520.0;

pub struct BoardCanvas<'a> {
    pub photo_assets: &'a PhotoBoardAssets,
    /// Keep the board at its width-derived scale and let the canvas clip the
    /// excess top/bottom instead of shrinking the whole instrument.
    pub compact_crop: bool,
    pub keys: &'a [Key],
    /// Maps KeyId → track index for color. usize::MAX = manually toggled (uses original colour).
    pub highlighted: &'a HashMap<KeyId, usize>,
    /// Optional live overlay (for browser MIDI input) drawn above the base
    /// playback/selection highlight without requiring a temporary merged map.
    pub overlay_highlighted: Option<&'a HashMap<KeyId, usize>>,
    /// Chronological play steps to badge onto highlighted keys while a staff
    /// range is selected. Chords share a number; repeated keys have several.
    pub play_order: Option<&'a HashMap<KeyId, Vec<usize>>>,
    /// Persistently-active control keys (e.g. layered waveform selects),
    /// independent of playback note overlays.
    pub selected_controls: &'a HashSet<KeyId>,
    /// Keys currently held with the pointer.
    pub pressed: &'a HashSet<KeyId>,
    /// Computer-key labels shown over the note names in performance mode.
    pub projected_labels: Option<&'a HashMap<KeyId, String>>,
    /// GM drum assignments for the numpad's 4x5 pad grid.
    pub drum_note_to_key: &'a HashMap<u8, KeyId>,
    /// Replace the numpad legends with instrument icons and names.
    pub show_drum_symbols: bool,
    /// Current 0.0..=1.0 dial position of each of the 12 encoder knobs.
    pub knob_values: &'a [f32],
}

/// The narrow grab rail attached to the bottom edge of the photographic board.
/// It owns the pointer drag state so resizing never enters the keyboard's much
/// busier note/knob event path.
pub struct BoardResizeHandle {
    pub current_height: f32,
    pub min_height: f32,
    pub max_height: f32,
}

#[derive(Debug, Clone, Copy)]
enum ResizePointer {
    Mouse,
    Touch(touch::Finger),
}

#[derive(Debug, Clone, Copy)]
struct ResizeDrag {
    pointer: ResizePointer,
    start_y: f32,
    start_height: f32,
}

#[derive(Default)]
pub struct BoardResizeState {
    drag: Option<ResizeDrag>,
}

fn resized_keyboard_height(start: f32, delta_y: f32, min: f32, max: f32) -> f32 {
    (start + delta_y).clamp(min.min(max), max.max(min))
}

impl canvas::Program<Message> for BoardResizeHandle {
    type State = BoardResizeState;

    fn update(
        &self,
        state: &mut Self::State,
        event: &canvas::Event,
        bounds: Rectangle,
        cursor: mouse::Cursor,
    ) -> Option<canvas::Action<Message>> {
        match event {
            canvas::Event::Mouse(mouse::Event::ButtonPressed(mouse::Button::Left)) => {
                let position = cursor.position()?;
                if bounds.contains(position) {
                    state.drag = Some(ResizeDrag {
                        pointer: ResizePointer::Mouse,
                        start_y: position.y,
                        start_height: self.current_height,
                    });
                    return Some(canvas::Action::capture());
                }
            }
            canvas::Event::Mouse(mouse::Event::CursorMoved { .. }) => {
                if let Some(ResizeDrag {
                    pointer: ResizePointer::Mouse,
                    start_y,
                    start_height,
                }) = state.drag
                {
                    if let Some(position) = cursor.position() {
                        let height = resized_keyboard_height(
                            start_height,
                            position.y - start_y,
                            self.min_height,
                            self.max_height,
                        );
                        return Some(
                            canvas::Action::publish(Message::KeyboardHeightChanged(height))
                                .and_capture(),
                        );
                    }
                }
            }
            canvas::Event::Mouse(mouse::Event::ButtonReleased(mouse::Button::Left)) => {
                if matches!(
                    state.drag.map(|drag| drag.pointer),
                    Some(ResizePointer::Mouse)
                ) {
                    state.drag = None;
                    return Some(canvas::Action::capture());
                }
            }
            canvas::Event::Touch(touch::Event::FingerPressed { id, position }) => {
                if state.drag.is_none() && bounds.contains(*position) {
                    state.drag = Some(ResizeDrag {
                        pointer: ResizePointer::Touch(*id),
                        start_y: position.y,
                        start_height: self.current_height,
                    });
                    return Some(canvas::Action::capture());
                }
            }
            canvas::Event::Touch(touch::Event::FingerMoved { id, position }) => {
                if let Some(ResizeDrag {
                    pointer: ResizePointer::Touch(active_id),
                    start_y,
                    start_height,
                }) = state.drag
                {
                    if *id == active_id {
                        let height = resized_keyboard_height(
                            start_height,
                            position.y - start_y,
                            self.min_height,
                            self.max_height,
                        );
                        return Some(
                            canvas::Action::publish(Message::KeyboardHeightChanged(height))
                                .and_capture(),
                        );
                    }
                }
            }
            canvas::Event::Touch(touch::Event::FingerLifted { id, .. })
            | canvas::Event::Touch(touch::Event::FingerLost { id, .. }) => {
                if matches!(
                    state.drag.map(|drag| drag.pointer),
                    Some(ResizePointer::Touch(active_id)) if active_id == *id
                ) {
                    state.drag = None;
                    return Some(canvas::Action::capture());
                }
            }
            _ => {}
        }

        None
    }

    fn draw(
        &self,
        state: &Self::State,
        renderer: &Renderer,
        _theme: &Theme,
        bounds: Rectangle,
        _cursor: mouse::Cursor,
    ) -> Vec<Geometry> {
        let mut frame = Frame::new(renderer, bounds.size());
        let width = frame.width();
        let height = frame.height();
        let active = state.drag.is_some();

        frame.fill(
            &Path::rectangle(Point::ORIGIN, frame.size()),
            rgb(0x11, 0x12, 0x0F),
        );
        frame.fill(
            &Path::rectangle(Point::new(0.0, 0.0), Size::new(width, 1.0)),
            rgb(0x3A, 0x39, 0x2E),
        );

        let grip_width = (width * 0.16).clamp(72.0, 220.0);
        let grip_x = (width - grip_width) / 2.0;
        let grip_color = if active {
            rgb(0xE9, 0x9B, 0x24)
        } else {
            rgb(0x91, 0x8C, 0x7D)
        };
        for offset in [-2.5, 2.5] {
            frame.fill(
                &rounded_rect(
                    Rectangle {
                        x: grip_x,
                        y: height / 2.0 + offset - 1.0,
                        width: grip_width,
                        height: 2.0,
                    },
                    1.0,
                ),
                grip_color,
            );
        }

        vec![frame.into_geometry()]
    }

    fn mouse_interaction(
        &self,
        state: &Self::State,
        bounds: Rectangle,
        cursor: mouse::Cursor,
    ) -> mouse::Interaction {
        if state.drag.is_some() || cursor.is_over(bounds) {
            mouse::Interaction::ResizingVertically
        } else {
            mouse::Interaction::default()
        }
    }
}

#[derive(Default)]
pub struct CanvasState {
    photo_cache: canvas::Cache,
    photo_crop_cache: canvas::Cache,
    overlay_cache: canvas::Cache,
    /// The knob drag popup gets its own geometry layer, separate from the
    /// crowded overlay frame — some large fills/thick strokes silently fail
    /// to render when they land late in a frame packed with hundreds of
    /// other draw calls (also seen on the numpad's drum-pad icons), and an
    /// isolated frame with far fewer prior draws reliably avoids it.
    slider_cache: canvas::Cache,
    /// Play-order badges get the same isolated-layer treatment as the knob
    /// slider popup — see `slider_cache`.
    badge_cache: canvas::Cache,
    /// The knob pointers (thin strokes, landing late in the same
    /// hundreds-of-draw-calls overlay frame as every key and the 13 knob
    /// face images) get the same isolated-layer treatment as `slider_cache`
    /// — otherwise they silently fail to render at all.
    knob_pointer_cache: canvas::Cache,
    pressed: Option<KeyId>,
    dragging_knob: Option<u8>,
    /// (cursor Y, knob value) captured on mouse-down, so dragging moves the
    /// value relative to where it already was instead of snapping it to
    /// whatever absolute position the click happened to land on — the knob
    /// itself sits above the pop-up track, so an absolute mapping always
    /// started the drag off the top or bottom of the track.
    drag_start: Option<(f32, f32)>,
}

/// Vertical extent of the pop-up slider shown while a knob is held, in
/// canvas-local coordinates. Cursor movement is mapped onto this range as a
/// delta from the drag's starting point (see `drag_start`), over a much
/// longer travel than the knob itself — far easier to land on a precise
/// setting than eyeballing rotation on a small dial.
fn knob_slider_track(knob_rect: Rectangle) -> (f32, f32) {
    let top = knob_rect.y + knob_rect.height + 22.0;
    (top, top + 160.0)
}

impl<'a> canvas::Program<Message> for BoardCanvas<'a> {
    type State = CanvasState;

    fn update(
        &self,
        state: &mut Self::State,
        event: &canvas::Event,
        bounds: Rectangle,
        cursor: mouse::Cursor,
    ) -> Option<canvas::Action<Message>> {
        match event {
            canvas::Event::Mouse(mouse::Event::ButtonPressed(mouse::Button::Left)) => {
                if let Some(pos) = cursor.position_in(bounds) {
                    for key in self.keys {
                        if key_rect_with_size(key, bounds.size(), self.compact_crop).contains(pos) {
                            if let Some(idx) = key.knob_index {
                                state.dragging_knob = Some(idx);
                                let current =
                                    self.knob_values.get(idx as usize).copied().unwrap_or(0.0);
                                // Anchor on the cursor's absolute (window) position, not the
                                // canvas-local one — `CursorMoved` below needs to keep tracking
                                // the drag even once the pointer leaves the canvas bounds
                                // (e.g. dragging a top-row knob upward past the board edge).
                                let start_y = cursor.position().map(|p| p.y).unwrap_or(pos.y);
                                state.drag_start = Some((start_y, current));
                                return Some(canvas::Action::capture());
                            }
                            state.pressed = Some(key.id);
                            return Some(
                                canvas::Action::publish(Message::KeyPressed(key.id)).and_capture(),
                            );
                        }
                    }
                }
            }
            canvas::Event::Mouse(mouse::Event::CursorMoved { .. }) => {
                if let Some(idx) = state.dragging_knob {
                    // Use the cursor's absolute position rather than
                    // `position_in(bounds)` — once the drag starts, the
                    // pointer is free to move outside the canvas (e.g.
                    // above a top-row knob) and should keep being tracked.
                    if let Some(pos) = cursor.position() {
                        if let Some(knob_rect) = self
                            .keys
                            .iter()
                            .find(|key| key.knob_index == Some(idx))
                            .map(|key| key_rect_with_size(key, bounds.size(), self.compact_crop))
                        {
                            let (top, bottom) = knob_slider_track(knob_rect);
                            let (start_y, start_value) = state.drag_start.unwrap_or((pos.y, 0.0));
                            let delta = (pos.y - start_y) / (bottom - top);
                            let value = (start_value - delta).clamp(0.0, 1.0);
                            return Some(
                                canvas::Action::publish(Message::KnobChanged(idx, value))
                                    .and_capture(),
                            );
                        }
                    }
                }
            }
            canvas::Event::Mouse(mouse::Event::ButtonReleased(mouse::Button::Left)) => {
                state.drag_start = None;
                if state.dragging_knob.take().is_some() {
                    return Some(canvas::Action::capture());
                }
                if let Some(id) = state.pressed.take() {
                    return Some(canvas::Action::publish(Message::KeyReleased(id)).and_capture());
                }
            }
            // Hovering a knob and scrolling nudges its value — much easier
            // than dragging to "turn" it, which is what click-drag simulates.
            canvas::Event::Mouse(mouse::Event::WheelScrolled { delta }) => {
                if let Some(pos) = cursor.position_in(bounds) {
                    for key in self.keys {
                        if key_rect_with_size(key, bounds.size(), self.compact_crop).contains(pos) {
                            if let Some(idx) = key.knob_index {
                                let amount = match *delta {
                                    mouse::ScrollDelta::Lines { y, .. } => y * 0.05,
                                    mouse::ScrollDelta::Pixels { y, .. } => y / 200.0,
                                };
                                let current =
                                    self.knob_values.get(idx as usize).copied().unwrap_or(0.0);
                                let value = (current + amount).clamp(0.0, 1.0);
                                return Some(
                                    canvas::Action::publish(Message::KnobChanged(idx, value))
                                        .and_capture(),
                                );
                            }
                            break;
                        }
                    }
                }
            }
            _ => {}
        }
        None
    }

    fn draw(
        &self,
        state: &Self::State,
        renderer: &Renderer,
        _theme: &Theme,
        bounds: Rectangle,
        _cursor: mouse::Cursor,
    ) -> Vec<Geometry> {
        state.overlay_cache.clear(); // highlights can change every 16 ms during playback
        state.knob_pointer_cache.clear(); // knob values can change just as often
        let active_knob = state.dragging_knob.map(|idx| {
            (
                idx,
                self.knob_values.get(idx as usize).copied().unwrap_or(0.0),
            )
        });
        let photo_cache = if self.compact_crop {
            &state.photo_crop_cache
        } else {
            &state.photo_cache
        };
        let photo_geometry = photo_cache.draw(renderer, bounds.size(), |frame| {
            frame.with_clip(canvas_clip(bounds.size()), |frame| {
                draw_board_base(frame, self.photo_assets, self.compact_crop);
            });
        });
        let mut badges: Vec<(Rectangle, Vec<usize>)> = Vec::new();
        let mut knob_pointers: Vec<(Rectangle, f32)> = Vec::new();
        let overlay_geometry = state.overlay_cache.draw(renderer, bounds.size(), |frame| {
            frame.with_clip(canvas_clip(bounds.size()), |frame| {
                draw_board_overlay(
                    frame,
                    self.photo_assets,
                    self.compact_crop,
                    self.keys,
                    self.highlighted,
                    self.overlay_highlighted,
                    self.play_order,
                    self.selected_controls,
                    self.pressed,
                    self.projected_labels,
                    self.drum_note_to_key,
                    self.show_drum_symbols,
                    self.knob_values,
                    active_knob,
                    &mut badges,
                    &mut knob_pointers,
                );
            });
        });
        // Keep interaction imagery separate from the cached photographic base
        // so active, colour-swapped key sprites render above the resting rows.
        let mut geometries = vec![photo_geometry, overlay_geometry];

        // The knob pointers are their own isolated geometry — see
        // `knob_pointer_cache`'s doc comment for why they can't just be the
        // last thing drawn into the (already large) overlay frame.
        if !knob_pointers.is_empty() {
            let pointer_geometry =
                state
                    .knob_pointer_cache
                    .draw(renderer, bounds.size(), |frame| {
                        frame.with_clip(canvas_clip(bounds.size()), |frame| {
                            for (rect, value) in &knob_pointers {
                                draw_knob_pointer(frame, *rect, *value);
                            }
                        });
                    });
            geometries.push(pointer_geometry);
        }

        // The knob drag popup is its own isolated geometry — see the
        // `slider_cache` doc comment for why it can't just be the last thing
        // drawn into the (already large) overlay frame.
        if let Some((idx, value)) = active_knob {
            state.slider_cache.clear();
            let slider_geometry = state.slider_cache.draw(renderer, bounds.size(), |frame| {
                if let Some(knob_rect) = self
                    .keys
                    .iter()
                    .find(|key| key.knob_index == Some(idx))
                    .map(|key| key_rect_with_size(key, bounds.size(), self.compact_crop))
                {
                    draw_knob_slider(frame, knob_rect, value, knob_readout(idx, value));
                }
            });
            geometries.push(slider_geometry);
        }

        // Play-order badges also get their own isolated geometry — see the
        // `badge_cache` doc comment.
        if !badges.is_empty() {
            state.badge_cache.clear();
            let badge_geometry = state.badge_cache.draw(renderer, bounds.size(), |frame| {
                for (rect, steps) in &badges {
                    draw_play_order_badge(frame, *rect, steps);
                }
            });
            geometries.push(badge_geometry);
        }

        geometries
    }

    fn mouse_interaction(
        &self,
        state: &Self::State,
        bounds: Rectangle,
        cursor: mouse::Cursor,
    ) -> mouse::Interaction {
        if state.dragging_knob.is_some() {
            return mouse::Interaction::ResizingVertically;
        }
        if let Some(pos) = cursor.position_in(bounds) {
            for key in self.keys {
                if key_rect_with_size(key, bounds.size(), self.compact_crop).contains(pos) {
                    if key.is_knob {
                        return mouse::Interaction::ResizingVertically;
                    }
                    return mouse::Interaction::Pointer;
                }
            }
        }
        mouse::Interaction::default()
    }
}

#[cfg(test)]
pub fn key_rect(key: &Key) -> Rectangle {
    key_rect_with_size(key, Size::new(1484.0, BASE_BOARD_HEIGHT), false)
}

fn key_rect_with_size(key: &Key, size: Size, compact_crop: bool) -> Rectangle {
    let canonical = match key.cluster {
        Cluster::Alpha | Cluster::AlphaLight => {
            let row = key.row as usize;
            let source = key_geometry::alpha_key_source_rect(row, key.col, key.w);
            let (source_width, _) = key_geometry::ALPHA_SOURCE_SIZES[row - 1];
            let source_scale = ALPHA_W / source_width;
            Rectangle {
                x: ALPHA_X + source.x * source_scale,
                y: ALPHA_Y + (key.row - 1.0) * ALPHA_ROW_PITCH,
                width: source.width * source_scale,
                height: ALPHA_ROW_PITCH,
            }
        }
        Cluster::Nav => Rectangle {
            x: NAV_X + (key.col - 15.5) * (NAV_W / 3.0),
            y: NAV_Y + (key.row - 1.0) * (NAV_H / 2.0),
            width: key.w * (NAV_W / 3.0),
            height: key.h * (NAV_H / 2.0),
        },
        Cluster::Arrow => Rectangle {
            x: ARROW_X + (key.col - 15.5) * (ARROW_W / 3.0),
            y: ARROW_Y + (key.row - 4.0) * (ARROW_H / 2.0),
            width: key.w * (ARROW_W / 3.0),
            height: key.h * (ARROW_H / 2.0),
        },
        Cluster::Numpad => {
            let source = key_geometry::numpad_key_source_rect(
                (key.col - 19.0).round() as usize,
                key.row.round() as usize,
            );
            let x_scale = NUMPAD_W / key_geometry::NUMPAD_SOURCE_SIZE.0;
            let y_scale = NUMPAD_H / key_geometry::NUMPAD_SOURCE_SIZE.1;
            Rectangle {
                x: NUMPAD_X + source.x * x_scale,
                y: NUMPAD_Y + source.y * y_scale,
                width: source.width * x_scale,
                height: source.height * y_scale,
            }
        }
        Cluster::Encoder => {
            let index = key.knob_index.unwrap_or(12);
            if index == 12 {
                let opening: Rectangle = Rectangle {
                    x: 102.0,
                    y: 187.0,
                    width: 100.0,
                    height: 90.0,
                };
                let diameter = opening.width.min(opening.height) * 0.9;
                Rectangle {
                    x: opening.x + (opening.width - diameter) / 2.0,
                    y: opening.y + (opening.height - diameter) / 2.0,
                    width: diameter,
                    height: diameter,
                }
            } else {
                let group = (index / 4) as usize;
                let within = (index % 4) as f32;
                let banks: [(f32, f32, f32, f32); 3] = [
                    (260.0, 323.0, 190.0, 87.0),
                    (611.0, 309.0, 188.0, 91.0),
                    (947.0, 310.0, 188.0, 90.0),
                ];
                let (bank_x, bank_width, bank_y, bank_height) = banks[group];
                let segment = bank_width / 4.0;
                let diameter = bank_height.min(segment) * 0.9;
                Rectangle {
                    x: bank_x + (within + 0.5) * segment - diameter / 2.0,
                    y: bank_y + (bank_height - diameter) / 2.0,
                    width: diameter,
                    height: diameter,
                }
            }
        }
    };
    photo_rect(
        size,
        compact_crop,
        canonical.x,
        canonical.y,
        canonical.width,
        canonical.height,
    )
}

fn key_sprite_rect_with_size(
    key: &Key,
    size: Size,
    compact_crop: bool,
    blank_numpad: bool,
) -> Rectangle {
    let rect = key_rect_with_size(key, size, compact_crop);
    let source_aspect = match key.cluster {
        Cluster::Alpha | Cluster::AlphaLight => {
            let row = (key.row as usize).saturating_sub(1).min(4);
            let crop = key_geometry::alpha_key_source_rect(row + 1, key.col, key.w);
            crop.width / crop.height
        }
        Cluster::Nav => (467.0 / 3.0 * key.w) / (308.0 / 2.0 * key.h),
        Cluster::Arrow => (456.0 / 3.0 * key.w) / (322.0 / 2.0 * key.h),
        Cluster::Numpad => {
            let column = (key.col - 19.0).round() as usize;
            let row = key.row.round() as usize;
            let crop = if blank_numpad {
                key_geometry::clean_numpad_key_source_rect(column, row)
            } else {
                key_geometry::numpad_key_source_rect(column, row)
            };
            crop.width / crop.height
        }
        Cluster::Encoder => return rect,
    };
    Rectangle {
        height: rect.width / source_aspect,
        ..rect
    }
}

fn alpha_source_rect_with_size(
    row: usize,
    source: SourceRect,
    size: Size,
    compact_crop: bool,
) -> Rectangle {
    let (source_width, _) = key_geometry::ALPHA_SOURCE_SIZES[row - 1];
    let row_y = ALPHA_Y + (row as f32 - 1.0) * ALPHA_ROW_PITCH;
    let row_origin = photo_rect(size, compact_crop, ALPHA_X, row_y, 0.0, 0.0);
    let scale = photo_rect(size, compact_crop, ALPHA_X, row_y, ALPHA_W, 0.0).width / source_width;
    Rectangle {
        x: row_origin.x + source.x * scale,
        y: row_origin.y + source.y * scale,
        width: source.width * scale,
        height: source.height * scale,
    }
}

fn alpha_text_guide_with_size(
    key: &Key,
    size: Size,
    compact_crop: bool,
) -> Option<(Point, Option<Rectangle>)> {
    let row = key.row as usize;
    match key_geometry::alpha_text_guide(row, key.col)? {
        TextGuide::Center { x, y } => {
            let point = alpha_source_rect_with_size(
                row,
                SourceRect {
                    x,
                    y,
                    width: 0.0,
                    height: 0.0,
                },
                size,
                compact_crop,
            );
            Some((Point::new(point.x, point.y), None))
        }
        TextGuide::Bounds(bounds) => {
            let bounds = alpha_source_rect_with_size(row, bounds, size, compact_crop);
            Some((
                Point::new(
                    bounds.x + bounds.width / 2.0,
                    bounds.y + bounds.height / 2.0,
                ),
                Some(bounds),
            ))
        }
    }
}

fn numpad_source_rect_with_size(source: SourceRect, size: Size, compact_crop: bool) -> Rectangle {
    let origin = photo_rect(size, compact_crop, NUMPAD_X, NUMPAD_Y, 0.0, 0.0);
    let opening = photo_rect(size, compact_crop, NUMPAD_X, NUMPAD_Y, NUMPAD_W, NUMPAD_H);
    let x_scale = opening.width / key_geometry::NUMPAD_SOURCE_SIZE.0;
    let y_scale = opening.height / key_geometry::NUMPAD_SOURCE_SIZE.1;
    Rectangle {
        x: origin.x + source.x * x_scale,
        y: origin.y + source.y * y_scale,
        width: source.width * x_scale,
        height: source.height * y_scale,
    }
}

fn numpad_text_bounds_with_size(key: &Key, size: Size, compact_crop: bool) -> Option<Rectangle> {
    let TextGuide::Bounds(bounds) = key_geometry::numpad_text_guide(
        (key.col - 19.0).round() as usize,
        key.row.round() as usize,
    )?
    else {
        return None;
    };
    Some(numpad_source_rect_with_size(bounds, size, compact_crop))
}

fn fill_text_with_bounds(frame: &mut Frame, mut text: Text, bounds: Option<Rectangle>) {
    if let Some(bounds) = bounds {
        if bounds.width <= 0.0 || bounds.height <= 0.0 {
            return;
        }
        // Iced's WebGL canvas drops cached text placed in a nested clip draft.
        // Constrain the paragraph and conservatively fit a single-line label
        // instead: even a full-em-wide glyph cannot cross the marked box.
        let glyph_count = text.content.chars().count().max(1) as f32;
        let width_limit = bounds.width * 0.86 / glyph_count;
        let height_limit = bounds.height * 0.45;
        text.size = iced::Pixels(text.size.0.min(width_limit).min(height_limit).max(3.0));
        text.max_width = bounds.width;
    }
    frame.fill_text(text);
}

/// Returns (filter_color, text_color) for a key.
/// `lit_track`: Some(track) when playing, None when unlit.
fn key_colors(cluster: Cluster, lit_track: Option<usize>) -> (Color, Color) {
    let lit = lit_track.is_some();

    // For MIDI keys, use the track colour; fall back to gold for non-MIDI clusters.
    // usize::MAX - 1 = out-of-range warning (nearest key to a note off the board)
    if lit_track == Some(usize::MAX - 1) {
        let fill = rgb(0xFF, 0x3D, 0x72);
        return (fill, Color::WHITE);
    }

    let track_fill = |default_r, default_g, default_b| -> (Color, Color) {
        match lit_track {
            Some(t) if t != usize::MAX => {
                let (r, g, b) = TRACK_COLORS[t % TRACK_COLORS.len()];
                (Color::from_rgb8(r, g, b), Color::BLACK)
            }
            _ => (rgb(default_r, default_g, default_b), Color::BLACK),
        }
    };

    let (fill, text) = match (cluster, lit) {
        (Cluster::Alpha, false) => (rgb(0x66, 0x75, 0x5E), Color::WHITE),
        (Cluster::Alpha, true) => track_fill(0xFF, 0xA3, 0x55),
        (Cluster::AlphaLight, false) => (rgb(0xDF, 0xE3, 0xD2), Color::BLACK),
        (Cluster::AlphaLight, true) => track_fill(0xFF, 0xA3, 0x55),
        (Cluster::Nav, false) => (rgb(0xC9, 0xC6, 0xBA), Color::BLACK),
        (Cluster::Nav, true) => (rgb(0xFF, 0xB4, 0x58), Color::BLACK),
        (Cluster::Arrow, false) => (rgb(0xCF, 0x7F, 0x6C), Color::BLACK),
        (Cluster::Arrow, true) => (rgb(0xFF, 0x4C, 0x82), Color::WHITE),
        (Cluster::Numpad, false) => (rgb(0xD9, 0xD4, 0xC8), Color::BLACK),
        (Cluster::Numpad, true) => (rgb(0x50, 0xD4, 0xC8), Color::BLACK),
        (Cluster::Encoder, _) => (rgb(0x1D, 0x1B, 0x28), Color::WHITE),
    };

    (fill, text)
}

fn rgb(r: u8, g: u8, b: u8) -> Color {
    Color::from_rgb8(r, g, b)
}

const PHOTO_WIDTH: f32 = 1949.0;
const PHOTO_HEIGHT: f32 = 807.0;
const COMPACT_CROP_X: f32 = 82.0;
const COMPACT_CROP_Y: f32 = 178.0;
const COMPACT_CROP_WIDTH: f32 = 1778.0;
const COMPACT_CROP_HEIGHT: f32 = 579.0;
pub const COMPACT_BOARD_ASPECT: f32 = COMPACT_CROP_WIDTH / COMPACT_CROP_HEIGHT;
const ALPHA_X: f32 = 124.0;
const ALPHA_Y: f32 = 346.0;
const ALPHA_W: f32 = 1129.0;
const ALPHA_H: f32 = 383.0;
const ALPHA_ROW_PITCH: f32 = 72.3;
const NAV_X: f32 = 1276.0;
const NAV_Y: f32 = 348.0;
const NAV_W: f32 = 228.0;
const NAV_H: f32 = 156.0;
const ARROW_X: f32 = 1278.0;
const ARROW_Y: f32 = 581.0;
const ARROW_W: f32 = 223.0;
const ARROW_H: f32 = 147.0;
const NUMPAD_X: f32 = 1534.0;
const NUMPAD_Y: f32 = 347.0;
const NUMPAD_W: f32 = 296.0;
const NUMPAD_H: f32 = 382.0;

fn canvas_clip(size: Size) -> Rectangle {
    Rectangle::new(Point::ORIGIN, size)
}

fn board_rect(size: Size, compact_crop: bool) -> Rectangle {
    let available = Rectangle {
        x: 2.0,
        y: 2.0,
        width: (size.width - 4.0).max(1.0),
        height: (size.height - 4.0).max(1.0),
    };
    let scale = if compact_crop {
        available.width / COMPACT_CROP_WIDTH
    } else {
        (available.width / PHOTO_WIDTH).min(available.height / PHOTO_HEIGHT)
    }
    .max(0.0001);
    let width = PHOTO_WIDTH * scale;
    let height = PHOTO_HEIGHT * scale;
    let (x, y) = if compact_crop {
        // Align the canonical working-surface crop to the viewport. If a user
        // drags the viewport shorter than the preset, retain the crop's center
        // while clipping equally from its top and bottom.
        let x = available.x - COMPACT_CROP_X * scale;
        let crop_center_y = COMPACT_CROP_Y + COMPACT_CROP_HEIGHT / 2.0;
        let desired_y = available.y + available.height / 2.0 - crop_center_y * scale;
        let min_y = available.y + available.height - height;
        let y = desired_y.clamp(min_y.min(available.y), min_y.max(available.y));
        (x, y)
    } else {
        (
            available.x + (available.width - width) / 2.0,
            available.y + (available.height - height) / 2.0,
        )
    };
    Rectangle {
        x,
        y,
        width,
        height,
    }
}

fn photo_rect(
    size: Size,
    compact_crop: bool,
    x: f32,
    y: f32,
    width: f32,
    height: f32,
) -> Rectangle {
    let board = board_rect(size, compact_crop);
    Rectangle {
        x: board.x + x / PHOTO_WIDTH * board.width,
        y: board.y + y / PHOTO_HEIGHT * board.height,
        width: width / PHOTO_WIDTH * board.width,
        height: height / PHOTO_HEIGHT * board.height,
    }
}

#[derive(Clone, Copy)]
struct TapeLabel {
    text: &'static str,
    x: f32,
    y: f32,
    size: f32,
}

fn draw_tape_labels(frame: &mut Frame, size: Size, compact_crop: bool) {
    let board = board_rect(size, compact_crop);
    let scale = board.width / PHOTO_WIDTH;
    let ink = Color::from_rgba8(0x20, 0x2A, 0x2D, 0.88);
    let labels = [
        TapeLabel {
            text: "BITCRUSH",
            x: 151.0,
            y: 132.0,
            size: 15.0,
        },
        TapeLabel {
            text: "VOL",
            x: 300.0,
            y: 132.0,
            size: 15.0,
        },
        TapeLabel {
            text: "CUTOFF",
            x: 381.0,
            y: 132.0,
            size: 13.0,
        },
        TapeLabel {
            text: "ATTACK",
            x: 462.0,
            y: 132.0,
            size: 13.0,
        },
        TapeLabel {
            text: "RELEASE",
            x: 543.0,
            y: 132.0,
            size: 12.0,
        },
        TapeLabel {
            text: "DECAY",
            x: 650.0,
            y: 132.0,
            size: 13.0,
        },
        TapeLabel {
            text: "SUSTAIN",
            x: 727.0,
            y: 132.0,
            size: 12.0,
        },
        TapeLabel {
            text: "DRUM\nVOL",
            x: 804.0,
            y: 132.0,
            size: 11.0,
        },
        TapeLabel {
            text: "PAN",
            x: 881.0,
            y: 132.0,
            size: 14.0,
        },
        TapeLabel {
            text: "VIB RATE",
            x: 986.0,
            y: 132.0,
            size: 11.0,
        },
        TapeLabel {
            text: "VIB DEPTH",
            x: 1063.0,
            y: 132.0,
            size: 10.5,
        },
        TapeLabel {
            text: "TREMOLO",
            x: 1141.0,
            y: 132.0,
            size: 11.0,
        },
        TapeLabel {
            text: "GLIDE",
            x: 1218.0,
            y: 132.0,
            size: 13.0,
        },
        TapeLabel {
            text: "MIDI\nSEND",
            x: 1594.0,
            y: 132.0,
            size: 13.0,
        },
        TapeLabel {
            text: "MIDI\nRECV",
            x: 1695.0,
            y: 132.0,
            size: 13.0,
        },
        TapeLabel {
            text: "STATUS",
            x: 1798.0,
            y: 132.0,
            size: 13.0,
        },
        TapeLabel {
            text: "HALL EFFECT SWITCHES",
            x: 751.0,
            y: 313.0,
            size: 11.0,
        },
        TapeLabel {
            text: "TRI",
            x: 1314.0,
            y: 313.0,
            size: 17.0,
        },
        TapeLabel {
            text: "SQR",
            x: 1390.0,
            y: 313.0,
            size: 17.0,
        },
        TapeLabel {
            text: "SAW",
            x: 1466.0,
            y: 313.0,
            size: 17.0,
        },
        TapeLabel {
            text: "SIN",
            x: 1314.0,
            y: 542.0,
            size: 17.0,
        },
        TapeLabel {
            text: "PULSE",
            x: 1390.0,
            y: 542.0,
            size: 13.0,
        },
        TapeLabel {
            text: "NOISE",
            x: 1466.0,
            y: 542.0,
            size: 13.0,
        },
        TapeLabel {
            text: "WICKI–HAYDEN  NOTE  LAYOUT",
            x: 715.0,
            y: 774.0,
            size: 18.0,
        },
        TapeLabel {
            text: "MIDI\nPITCH\nDOWN",
            x: 1320.0,
            y: 770.0,
            size: 11.0,
        },
        TapeLabel {
            text: "MIDI\nPITCH\nUP",
            x: 1454.0,
            y: 770.0,
            size: 11.0,
        },
        TapeLabel {
            text: "DRUMS",
            x: 1690.0,
            y: 770.0,
            size: 20.0,
        },
    ];

    for label in labels {
        let point = Point::new(board.x + label.x * scale, board.y + label.y * scale);
        frame.fill_text(Text {
            content: label.text.to_string(),
            position: point,
            color: ink,
            size: iced::Pixels((label.size * scale).max(4.0)),
            font: TAPE_FONT,
            align_x: Horizontal::Center.into(),
            align_y: Vertical::Center,
            ..Text::default()
        });
    }

    frame.fill_text(Text {
        content: "THE\nKEYBOARD²".to_string(),
        position: Point::new(board.x + 55.0 * scale, board.y + 525.0 * scale),
        color: ink,
        size: iced::Pixels((12.0 * scale).max(4.0)),
        font: TAPE_FONT,
        align_x: Horizontal::Center.into(),
        align_y: Vertical::Center,
        ..Text::default()
    });
}

fn contained_rect(target: Rectangle, source_width: f32, source_height: f32) -> Rectangle {
    let scale = (target.width / source_width).min(target.height / source_height);
    let width = source_width * scale;
    let height = source_height * scale;
    Rectangle {
        x: target.x + (target.width - width) / 2.0,
        y: target.y + (target.height - height) / 2.0,
        width,
        height,
    }
}

fn draw_board_base(frame: &mut Frame, photo_assets: &PhotoBoardAssets, compact_crop: bool) {
    let size = frame.size();
    let board = board_rect(size, compact_crop);

    frame.fill(&Path::rectangle(Point::ORIGIN, size), rgb(0x09, 0x0D, 0x0E));
    let shadow = rounded_rect(
        Rectangle {
            x: board.x + 3.0,
            y: board.y + 7.0,
            ..board
        },
        14.0,
    );
    frame.fill(&shadow, Color::from_rgba8(0, 0, 0, 0.62));

    for (x, y, width, height) in [
        (102.0, 187.0, 100.0, 90.0),
        (260.0, 190.0, 323.0, 87.0),
        (611.0, 188.0, 309.0, 91.0),
        (947.0, 188.0, 310.0, 90.0),
        (1282.0, 187.0, 233.0, 90.0),
        (1543.0, 189.0, 305.0, 89.0),
        (ALPHA_X, ALPHA_Y, ALPHA_W, ALPHA_H),
        (NAV_X, NAV_Y, NAV_W, NAV_H),
        (ARROW_X, ARROW_Y, ARROW_W, ARROW_H),
        (NUMPAD_X, NUMPAD_Y, NUMPAD_W, NUMPAD_H),
    ] {
        let rect = photo_rect(size, compact_crop, x, y, width, height);
        frame.fill(
            &Path::rectangle(Point::new(rect.x, rect.y), rect.size()),
            rgb(0x07, 0x09, 0x08),
        );
    }

    frame.draw_image(board, &photo_assets.shell);
    // The display cutout gets no separate glass image at all — its status
    // text (see `draw_board_overlay`) sits directly on the near-black cutout
    // fill drawn above, in the same dark-panel-plus-amber-text material as
    // the header LCD (see `LCD_BG`/`LCD_TEXT` in main.rs), rather than a
    // mismatched photographed backlight color.
    frame.draw_image(
        contained_rect(
            photo_rect(size, compact_crop, 1543.0, 189.0, 305.0, 89.0),
            577.0,
            175.0,
        ),
        &photo_assets.leds,
    );
}

fn draw_board_overlay(
    frame: &mut Frame,
    photo_assets: &PhotoBoardAssets,
    compact_crop: bool,
    keys: &[Key],
    highlighted: &HashMap<KeyId, usize>,
    overlay_highlighted: Option<&HashMap<KeyId, usize>>,
    play_order: Option<&HashMap<KeyId, Vec<usize>>>,
    selected_controls: &HashSet<KeyId>,
    pressed: &HashSet<KeyId>,
    projected_labels: Option<&HashMap<KeyId, String>>,
    drum_note_to_key: &HashMap<u8, KeyId>,
    show_drum_symbols: bool,
    knob_values: &[f32],
    active_knob: Option<(u8, f32)>,
    badges: &mut Vec<(Rectangle, Vec<usize>)>,
    knob_pointers: &mut Vec<(Rectangle, f32)>,
) {
    let size = frame.size();
    let display_bezel_rect = photo_rect(size, compact_crop, 1282.0, 187.0, 233.0, 90.0);
    let display_text = active_knob
        .and_then(|(idx, value)| knob_readout(idx, value))
        .unwrap_or_else(|| "MIDI READY".to_string());
    frame.fill_text(Text {
        content: display_text,
        position: Point::new(
            display_bezel_rect.x + display_bezel_rect.width / 2.0,
            display_bezel_rect.y + display_bezel_rect.height / 2.0,
        ),
        // Same amber as the header LCD's own readout text (`LCD_TEXT` in
        // main.rs) — one on-board display, one off-board, same material.
        color: rgb(0xE9, 0x9B, 0x24),
        size: iced::Pixels(
            (board_rect(size, compact_crop).width / PHOTO_WIDTH * 14.0).clamp(7.0, 14.0),
        ),
        font: CANVAS_FONT,
        align_x: Horizontal::Center.into(),
        align_y: Vertical::Center,
        ..Text::default()
    });

    draw_tape_labels(frame, size, compact_crop);

    for key in keys {
        let rect = key_rect_with_size(key, size, compact_crop);
        let lit_track = overlay_highlighted
            .and_then(|overlay| overlay.get(&key.id))
            .copied()
            .or_else(|| highlighted.get(&key.id).copied())
            .or_else(|| {
                (selected_controls.contains(&key.id) || pressed.contains(&key.id))
                    .then_some(usize::MAX)
            });

        if key.is_knob {
            let value = key
                .knob_index
                .and_then(|idx| knob_values.get(idx as usize))
                .copied()
                .unwrap_or(0.0);
            let label = key
                .knob_index
                .and_then(|idx| crate::synth::KNOB_PARAMS.get(idx as usize))
                .map(|param| param.label);
            draw_knob(frame, rect, label, &photo_assets.knob_face);
            knob_pointers.push((rect, value));
            continue;
        }

        let (_, text_color) = key_colors(key.cluster, lit_track);
        let press_offset = lit_track
            .map(|_| (rect.height * 0.055).clamp(1.0, 4.0))
            .unwrap_or(0.0);
        let mut sprite_rect = key_sprite_rect_with_size(key, size, compact_crop, show_drum_symbols);
        sprite_rect.y += press_offset;
        if let Some(sprite) = photo_assets.key_sprite(key, lit_track, show_drum_symbols) {
            frame.draw_image(sprite_rect, &sprite);
        }
        let visual_rect = Rectangle {
            y: rect.y + press_offset,
            ..rect
        };

        let drum_note = show_drum_symbols
            .then(|| {
                drum_note_to_key
                    .iter()
                    .find_map(|(&note, &id)| (id == key.id).then_some(note))
            })
            .flatten();
        let projected_label = projected_labels.and_then(|labels| labels.get(&key.id));

        if let Some(note) = drum_note {
            let label_rect = if matches!(key.cluster, Cluster::Numpad) {
                if let Some(mut bounds) = numpad_text_bounds_with_size(key, size, compact_crop) {
                    bounds.y += press_offset;
                    bounds
                } else {
                    visual_rect
                }
            } else {
                visual_rect
            };
            draw_drum_symbol(
                frame,
                label_rect,
                note,
                text_color,
                projected_label.map(String::as_str),
            );
            if let Some(steps) = play_order.and_then(|order| order.get(&key.id)) {
                badges.push((visual_rect, steps.clone()));
            }
            continue;
        }

        let (primary_label, secondary_label) = match key.cluster {
            Cluster::Alpha | Cluster::AlphaLight => (
                projected_label.map(String::as_str).unwrap_or(key.label),
                if projected_label.is_some() {
                    Some(key.label)
                } else {
                    None
                },
            ),
            Cluster::Nav | Cluster::Arrow => {
                (projected_label.map(String::as_str).unwrap_or(""), None)
            }
            // The numpad's computer-key labels only ever add information as
            // the small corner hint drawn by `draw_drum_symbol` above, once
            // drum symbols replace its photographed digits. Outside that
            // mode the real photographed numpad already shows the same
            // digit, so drawing it again here would just double it.
            Cluster::Numpad => ("", None),
            Cluster::Encoder => unreachable!(),
        };

        let board_scale = board_rect(size, compact_crop).width / PHOTO_WIDTH;
        let (label_anchor, label_bounds) =
            if matches!(key.cluster, Cluster::Alpha | Cluster::AlphaLight) {
                if let Some((mut anchor, mut bounds)) =
                    alpha_text_guide_with_size(key, size, compact_crop)
                {
                    anchor.y += press_offset;
                    if let Some(region) = bounds.as_mut() {
                        region.y += press_offset;
                    }
                    (anchor, bounds)
                } else {
                    (
                        Point::new(
                            visual_rect.x + visual_rect.width / 2.0,
                            visual_rect.y + visual_rect.height / 2.0,
                        ),
                        None,
                    )
                }
            } else {
                (
                    Point::new(
                        visual_rect.x + visual_rect.width / 2.0,
                        visual_rect.y + visual_rect.height / 2.0,
                    ),
                    None,
                )
            };

        if !primary_label.is_empty() {
            fill_text_with_bounds(
                frame,
                Text {
                    content: primary_label.to_string(),
                    position: Point::new(
                        label_anchor.x,
                        label_anchor.y
                            - if secondary_label.is_some() {
                                6.0 * board_scale
                            } else {
                                0.0
                            },
                    ),
                    color: text_color,
                    size: iced::Pixels(
                        ((if primary_label.len() > 4 { 11.0 } else { 14.0 }) * board_scale)
                            .clamp(5.0, 14.0),
                    ),
                    font: CANVAS_FONT,
                    align_x: Horizontal::Center.into(),
                    align_y: Vertical::Center,
                    ..Text::default()
                },
                label_bounds,
            );
        }

        if let Some(sub) = secondary_label {
            fill_text_with_bounds(
                frame,
                Text {
                    content: sub.to_string(),
                    position: Point::new(label_anchor.x, label_anchor.y + 12.0 * board_scale),
                    color: Color::from_rgba8(0, 0, 0, 0.6),
                    size: iced::Pixels((10.0 * board_scale).clamp(4.0, 10.0)),
                    font: CANVAS_FONT,
                    align_x: Horizontal::Center.into(),
                    align_y: Vertical::Center,
                    ..Text::default()
                },
                label_bounds,
            );
        }

        if let Some(steps) = play_order.and_then(|order| order.get(&key.id)) {
            badges.push((visual_rect, steps.clone()));
        }
    }
}

fn drum_pad_name(note: u8) -> Option<&'static str> {
    Some(match note {
        36 => "KICK",
        37 => "STICK",
        38 => "SNARE",
        39 => "CLAP",
        40 => "E.SNARE",
        41 => "LO FLOOR",
        42 => "CLOSED HH",
        43 => "HI FLOOR",
        44 => "PEDAL HH",
        45 => "LOW TOM",
        46 => "OPEN HH",
        47 => "LO-MID",
        48 => "HI-MID",
        49 => "CRASH",
        50 => "HIGH TOM",
        51 => "RIDE",
        52 => "CHINA",
        53 => "RIDE BELL",
        54 => "TAMBO",
        55 => "SPLASH",
        _ => return None,
    })
}

fn icon_line(frame: &mut Frame, from: Point, to: Point, color: Color, width: f32) {
    frame.stroke(
        &Path::line(from, to),
        canvas::Stroke::default()
            .with_color(color)
            .with_width(width),
    );
}

fn draw_drum_body(frame: &mut Frame, center: Point, color: Color, floor_legs: bool) {
    let body = rounded_rect(
        Rectangle {
            x: center.x - 9.0,
            y: center.y - 6.0,
            width: 18.0,
            height: 12.0,
        },
        3.0,
    );
    frame.stroke(
        &body,
        canvas::Stroke::default().with_color(color).with_width(1.7),
    );
    icon_line(
        frame,
        Point::new(center.x - 8.0, center.y - 2.0),
        Point::new(center.x + 8.0, center.y - 2.0),
        color,
        1.2,
    );
    if floor_legs {
        icon_line(
            frame,
            Point::new(center.x - 6.0, center.y + 6.0),
            Point::new(center.x - 8.0, center.y + 10.0),
            color,
            1.5,
        );
        icon_line(
            frame,
            Point::new(center.x + 6.0, center.y + 6.0),
            Point::new(center.x + 8.0, center.y + 10.0),
            color,
            1.5,
        );
    }
}

fn draw_hi_hat(frame: &mut Frame, center: Point, color: Color, open: bool, pedal: bool) {
    let spread = if open { 3.5 } else { 1.5 };
    icon_line(
        frame,
        Point::new(center.x - 9.0, center.y - spread),
        Point::new(center.x + 9.0, center.y - spread),
        color,
        1.7,
    );
    icon_line(
        frame,
        Point::new(center.x - 9.0, center.y + spread),
        Point::new(center.x + 9.0, center.y + spread),
        color,
        1.7,
    );
    icon_line(
        frame,
        Point::new(center.x, center.y + spread),
        Point::new(center.x, center.y + 10.0),
        color,
        1.4,
    );
    icon_line(
        frame,
        Point::new(center.x - 6.0, center.y + 10.0),
        Point::new(center.x + 6.0, center.y + 10.0),
        color,
        1.4,
    );
    if pedal {
        icon_line(
            frame,
            Point::new(center.x, center.y + 7.0),
            Point::new(center.x + 8.0, center.y + 10.0),
            color,
            1.5,
        );
    }
}

fn draw_cymbal(frame: &mut Frame, center: Point, color: Color, small: bool) {
    let half_width = if small { 7.0 } else { 11.0 };
    let cymbal = Path::new(|b| {
        b.move_to(Point::new(center.x - half_width, center.y));
        b.quadratic_curve_to(
            Point::new(center.x, center.y - 4.0),
            Point::new(center.x + half_width, center.y),
        );
    });
    frame.stroke(
        &cymbal,
        canvas::Stroke::default().with_color(color).with_width(1.8),
    );
    frame.fill(
        &Path::circle(Point::new(center.x, center.y - 2.0), 2.0),
        color,
    );
    icon_line(
        frame,
        Point::new(center.x, center.y),
        Point::new(center.x, center.y + 10.0),
        color,
        1.4,
    );
    icon_line(
        frame,
        Point::new(center.x - 5.0, center.y + 10.0),
        Point::new(center.x + 5.0, center.y + 10.0),
        color,
        1.4,
    );
}

/// Draw a small pictogram plus a compact GM instrument name. The text keeps
/// closely-related toms and cymbals unambiguous, while the shapes remain easy
/// to scan during performance.
fn draw_drum_symbol(
    frame: &mut Frame,
    rect: Rectangle,
    note: u8,
    color: Color,
    computer_key: Option<&str>,
) {
    let Some(name) = drum_pad_name(note) else {
        return;
    };
    // The numpad row's real photographed key face only fills roughly the
    // bottom 80% of its cell (the top is the switch-well shadow), so a fixed
    // pixel offset from the cell top can land in that shadow instead of on
    // the cap. Anchor both the icon and the name proportionally within the
    // cell so they land on the visible cap at any window size.
    let cap_top = rect.y + rect.height * 0.22;
    let center = Point::new(rect.x + rect.width / 2.0, cap_top + rect.height * 0.20);

    match note {
        36 => {
            let drum = Path::circle(center, 9.0);
            frame.stroke(
                &drum,
                canvas::Stroke::default().with_color(color).with_width(1.8),
            );
            frame.fill(&Path::circle(center, 2.2), color);
            icon_line(
                frame,
                Point::new(center.x - 6.0, center.y + 7.0),
                Point::new(center.x - 9.0, center.y + 11.0),
                color,
                1.4,
            );
            icon_line(
                frame,
                Point::new(center.x + 6.0, center.y + 7.0),
                Point::new(center.x + 9.0, center.y + 11.0),
                color,
                1.4,
            );
        }
        37 => {
            icon_line(
                frame,
                Point::new(center.x - 8.0, center.y + 8.0),
                Point::new(center.x + 8.0, center.y - 8.0),
                color,
                2.2,
            );
            icon_line(
                frame,
                Point::new(center.x - 8.0, center.y - 8.0),
                Point::new(center.x + 8.0, center.y + 8.0),
                color,
                2.2,
            );
            frame.fill(
                &Path::circle(Point::new(center.x - 8.0, center.y + 8.0), 1.8),
                color,
            );
            frame.fill(
                &Path::circle(Point::new(center.x + 8.0, center.y + 8.0), 1.8),
                color,
            );
        }
        38 | 40 => {
            draw_drum_body(frame, center, color, false);
            if note == 40 {
                let bolt = Path::new(|b| {
                    b.move_to(Point::new(center.x + 1.0, center.y - 8.0));
                    b.line_to(Point::new(center.x - 2.0, center.y - 1.0));
                    b.line_to(Point::new(center.x + 2.0, center.y - 1.0));
                    b.line_to(Point::new(center.x - 1.0, center.y + 7.0));
                });
                frame.stroke(
                    &bolt,
                    canvas::Stroke::default().with_color(color).with_width(1.4),
                );
            }
        }
        39 => {
            let hand = rounded_rect(
                Rectangle {
                    x: center.x - 6.0,
                    y: center.y - 1.0,
                    width: 12.0,
                    height: 10.0,
                },
                3.0,
            );
            frame.stroke(
                &hand,
                canvas::Stroke::default().with_color(color).with_width(1.5),
            );
            for offset in [-6.0, -2.0, 2.0, 6.0] {
                icon_line(
                    frame,
                    Point::new(center.x + offset, center.y - 1.0),
                    Point::new(center.x + offset, center.y - 9.0 + offset.abs() * 0.25),
                    color,
                    1.5,
                );
            }
        }
        41 | 43 => {
            draw_drum_body(frame, center, color, true);
            let dot_y = if note == 41 {
                center.y + 2.0
            } else {
                center.y - 4.0
            };
            frame.fill(&Path::circle(Point::new(center.x, dot_y), 1.8), color);
        }
        42 => draw_hi_hat(frame, center, color, false, false),
        44 => draw_hi_hat(frame, center, color, false, true),
        46 => draw_hi_hat(frame, center, color, true, false),
        45 | 47 | 48 | 50 => {
            draw_drum_body(frame, center, color, false);
            let dot_y = match note {
                45 => center.y + 3.0,
                47 => center.y + 1.0,
                48 => center.y - 2.0,
                _ => center.y - 4.0,
            };
            frame.fill(&Path::circle(Point::new(center.x, dot_y), 1.8), color);
        }
        49 => {
            draw_cymbal(frame, center, color, false);
            for (dx, dy) in [(-12.0, -5.0), (12.0, -5.0), (0.0, -11.0)] {
                icon_line(
                    frame,
                    Point::new(center.x + dx * 0.72, center.y + dy * 0.72),
                    Point::new(center.x + dx, center.y + dy),
                    color,
                    1.2,
                );
            }
        }
        51 => draw_cymbal(frame, center, color, false),
        52 => {
            let china = Path::new(|b| {
                b.move_to(Point::new(center.x - 11.0, center.y - 3.0));
                b.quadratic_curve_to(
                    Point::new(center.x, center.y + 5.0),
                    Point::new(center.x + 11.0, center.y - 3.0),
                );
            });
            frame.stroke(
                &china,
                canvas::Stroke::default().with_color(color).with_width(1.8),
            );
            frame.fill(&Path::circle(Point::new(center.x, center.y), 2.0), color);
            icon_line(
                frame,
                Point::new(center.x, center.y + 1.0),
                Point::new(center.x, center.y + 10.0),
                color,
                1.4,
            );
        }
        53 => {
            let bell = Path::new(|b| {
                b.move_to(Point::new(center.x - 8.0, center.y + 6.0));
                b.quadratic_curve_to(
                    Point::new(center.x - 5.0, center.y - 7.0),
                    Point::new(center.x, center.y - 8.0),
                );
                b.quadratic_curve_to(
                    Point::new(center.x + 5.0, center.y - 7.0),
                    Point::new(center.x + 8.0, center.y + 6.0),
                );
                b.line_to(Point::new(center.x - 8.0, center.y + 6.0));
            });
            frame.stroke(
                &bell,
                canvas::Stroke::default().with_color(color).with_width(1.7),
            );
            frame.fill(
                &Path::circle(Point::new(center.x, center.y + 8.0), 2.0),
                color,
            );
        }
        54 => {
            let ring = Path::circle(center, 8.0);
            frame.stroke(
                &ring,
                canvas::Stroke::default().with_color(color).with_width(1.8),
            );
            for (dx, dy) in [
                (0.0, -10.0),
                (9.0, -4.0),
                (9.0, 4.0),
                (0.0, 10.0),
                (-9.0, 4.0),
                (-9.0, -4.0),
            ] {
                frame.fill(
                    &Path::circle(Point::new(center.x + dx, center.y + dy), 1.7),
                    color,
                );
            }
        }
        55 => {
            draw_cymbal(frame, center, color, true);
            for (dx, dy) in [(-9.0, -7.0), (0.0, -11.0), (9.0, -7.0)] {
                icon_line(
                    frame,
                    Point::new(center.x + dx * 0.7, center.y + dy * 0.7),
                    Point::new(center.x + dx, center.y + dy),
                    color,
                    1.2,
                );
            }
        }
        _ => {}
    }

    if let Some(key) = computer_key {
        fill_text_with_bounds(
            frame,
            Text {
                content: key.to_string(),
                position: Point::new(rect.x + 5.0, cap_top + 4.0),
                color: Color { a: 0.58, ..color },
                size: iced::Pixels(7.0),
                font: CANVAS_FONT,
                align_x: Horizontal::Left.into(),
                ..Text::default()
            },
            Some(rect),
        );
    }

    fill_text_with_bounds(
        frame,
        Text {
            content: name.to_string(),
            position: Point::new(rect.x + rect.width / 2.0, rect.y + rect.height * 0.90),
            color,
            size: iced::Pixels(if name.len() > 8 { 7.0 } else { 8.0 }),
            font: CANVAS_FONT,
            align_x: Horizontal::Center.into(),
            align_y: Vertical::Center,
            ..Text::default()
        },
        Some(rect),
    );
}

/// Draws a compact, high-contrast sequence badge in the key's upper-right
/// corner. A repeated key reads e.g. "2·5"; simultaneous chord keys all show
/// the same number.
fn draw_play_order_badge(frame: &mut Frame, key_rect: Rectangle, steps: &[usize]) {
    if steps.is_empty() {
        return;
    }

    let label = steps
        .iter()
        .map(usize::to_string)
        .collect::<Vec<_>>()
        .join("·");
    let char_count = label.chars().count().max(1) as f32;
    let width = (char_count * 6.0 + 10.0).clamp(18.0, key_rect.width - 8.0);
    let height: f32 = 18.0;
    let badge = Rectangle {
        x: key_rect.x + key_rect.width - width - 4.0,
        y: key_rect.y + 4.0,
        width,
        height: height.min(key_rect.height - 8.0),
    };
    let path = Path::rectangle(Point::new(badge.x, badge.y), badge.size());
    frame.fill(&path, Color::from_rgba8(0x2A, 0x25, 0x20, 0.92));
    frame.stroke(
        &path,
        canvas::Stroke::default()
            .with_color(Color::from_rgba8(0xFF, 0xFF, 0xFF, 0.78))
            .with_width(1.0),
    );

    // Long repeated-note sequences shrink to stay inside their key rather
    // than spilling across adjacent labels.
    let font_size = (width / (char_count * 0.62)).clamp(6.0, 10.0);
    frame.fill_text(Text {
        content: label,
        position: Point::new(badge.x + badge.width / 2.0, badge.y + badge.height / 2.0),
        color: Color::WHITE,
        size: iced::Pixels(font_size),
        font: CANVAS_FONT,
        align_x: Horizontal::Center.into(),
        align_y: Vertical::Center,
        ..Text::default()
    });
}

/// Formats a knob's current position as "<label> <real value>" (e.g.
/// "Volume 1.00"), scaling the normalized 0.0..=1.0 dial position into the
/// parameter's real engine units via `KNOB_PARAMS`.
fn knob_readout(idx: u8, value: f32) -> Option<String> {
    crate::synth::KNOB_PARAMS.get(idx as usize).map(|param| {
        let real = param.min + value.clamp(0.0, 1.0) * (param.max - param.min);
        format!("{} {:.2}", param.label, real)
    })
}

fn draw_knob_slider(frame: &mut Frame, knob_rect: Rectangle, value: f32, readout: Option<String>) {
    let (top, bottom) = knob_slider_track(knob_rect);
    let center_x = knob_rect.x + knob_rect.width / 2.0;
    let value = value.clamp(0.0, 1.0);
    // Panel width must track the readout text ("Vib Depth 50.00" is the
    // longest label+value pair) — a fixed width let long labels overflow
    // the opaque background onto the keys behind, making them unreadable.
    let panel_width = readout
        .as_ref()
        .map(|text| (text.len() as f32 * 7.2 + 28.0).max(100.0))
        .unwrap_or(100.0);

    let panel = rounded_rect(
        Rectangle {
            x: center_x - panel_width / 2.0,
            y: top - 30.0,
            width: panel_width,
            height: (bottom - top) + 40.0,
        },
        8.0,
    );
    // Very dark, low-RGB fill colors (roughly below 0x20 per channel) render
    // as invisible or badly washed out in this app's canvas pipeline even at
    // full alpha, while otherwise-identical strokes render correctly — this
    // panel used to be near-black (0x11,0x13,0x0F) and never appeared at
    // all. Kept dark but nudged into a range that actually paints.
    frame.fill(&panel, Color::from_rgba8(0x20, 0x1E, 0x2A, 0.97));
    frame.stroke(
        &panel,
        canvas::Stroke::default()
            .with_color(rgb(0x75, 0x6B, 0x4E))
            .with_width(1.0),
    );

    if let Some(readout) = readout {
        frame.fill_text(Text {
            content: readout,
            position: Point::new(center_x, top - 14.0),
            color: rgb(0xFF, 0xD3, 0x9B),
            size: iced::Pixels(12.0),
            font: CANVAS_FONT,
            align_x: Horizontal::Center.into(),
            align_y: Vertical::Center,
            ..Text::default()
        });
    }

    let track = rounded_rect(
        Rectangle {
            x: center_x - 3.0,
            y: top,
            width: 6.0,
            height: bottom - top,
        },
        3.0,
    );
    frame.fill(&track, rgb(0x25, 0x27, 0x1D));

    let handle_y = top + (1.0 - value) * (bottom - top);
    let filled = rounded_rect(
        Rectangle {
            x: center_x - 3.0,
            y: handle_y,
            width: 6.0,
            height: bottom - handle_y,
        },
        3.0,
    );
    frame.fill(&filled, rgb(0xFF, 0x76, 0x7B));

    let handle = Path::circle(Point::new(center_x, handle_y), 8.0);
    frame.fill(&handle, rgb(0xFF, 0x76, 0x7B));
    frame.stroke(
        &handle,
        canvas::Stroke::default()
            .with_color(Color::WHITE)
            .with_width(1.5),
    );
}

fn rounded_rect(rect: Rectangle, radius: f32) -> Path {
    Path::new(|builder| {
        builder.rounded_rectangle(
            Point::new(rect.x, rect.y),
            Size::new(rect.width, rect.height),
            radius.into(),
        );
    })
}

fn draw_knob(
    frame: &mut Frame,
    rect: Rectangle,
    label: Option<&str>,
    face: &iced::widget::image::Handle,
) {
    let center = Point::new(rect.x + rect.width / 2.0, rect.y + rect.height / 2.0);
    let radius = rect.width.min(rect.height) / 2.0 - 4.0;

    frame.fill(
        &Path::circle(Point::new(center.x, center.y + 3.0), radius + 1.0),
        Color::from_rgba8(0, 0, 0, 0.45),
    );

    // Tick ring, same -135°..+135° sweep as the pointer, matching the mixer's
    // CH/OCT knob dial (see `rotary_knob`/`KnobDial` in main.rs) so both
    // control families read as one manufactured product.
    const TICKS: usize = 11;
    const SWEEP_DEG: f32 = 270.0;
    for i in 0..TICKS {
        let t = i as f32 / (TICKS - 1) as f32;
        let tick_angle = (-SWEEP_DEG / 2.0 + t * SWEEP_DEG).to_radians();
        let (s, c) = tick_angle.sin_cos();
        let tall = i == 0 || i == TICKS - 1 || i == TICKS / 2;
        let inner = radius - if tall { radius * 0.22 } else { radius * 0.12 };
        let outer = radius + 1.0;
        frame.stroke(
            &Path::line(
                Point::new(center.x + s * inner, center.y - c * inner),
                Point::new(center.x + s * outer, center.y - c * outer),
            ),
            canvas::Stroke::default()
                .with_color(Color::from_rgba8(0xB8, 0xAD, 0x8E, 0.5))
                .with_width(1.0),
        );
    }

    let face_size = radius * 1.6;
    frame.draw_image(
        Rectangle::new(
            Point::new(center.x - face_size / 2.0, center.y - face_size / 2.0),
            Size::new(face_size, face_size),
        ),
        face,
    );

    // The pointer itself is drawn later, in its own isolated geometry layer
    // — see `knob_pointer_cache`'s doc comment. A thin stroke this late in a
    // frame already packed with 13 knob images and ~100 other keys silently
    // fails to render at all; it needs to be the only thing in its frame.
    if let Some(label) = label {
        let label_size = (rect.width * 0.16).clamp(4.0, 8.0);
        frame.fill_text(Text {
            content: label.to_string(),
            position: Point::new(center.x, rect.y + rect.height + label_size + 1.0),
            color: rgb(0xB8, 0xAD, 0x8E),
            size: iced::Pixels(label_size),
            font: CANVAS_FONT,
            align_x: Horizontal::Center.into(),
            align_y: Vertical::Center,
            ..Text::default()
        });
    }
}

/// Draws one knob's pointer, tip, and center pin — split out of [`draw_knob`]
/// into its own isolated geometry layer (see `knob_pointer_cache`'s doc
/// comment) since a thin stroke this late in the packed overlay frame
/// silently fails to render at all.
fn draw_knob_pointer(frame: &mut Frame, rect: Rectangle, value: f32) {
    let center = Point::new(rect.x + rect.width / 2.0, rect.y + rect.height / 2.0);
    let radius = rect.width.min(rect.height) / 2.0 - 4.0;

    // Sweeps -135°..+135° (bottom-left to bottom-right through the top) as
    // `value` goes 0.0..=1.0, mirroring a real knob's travel.
    let angle = -135f32.to_radians() + value.clamp(0.0, 1.0) * 270f32.to_radians();
    let (s, c) = (angle.sin(), angle.cos());
    let inner = radius * 0.35;
    let outer = radius * 0.85;
    let tip = Point::new(center.x + s * outer, center.y - c * outer);
    let pointer = Path::new(|b| {
        b.move_to(Point::new(center.x + s * inner, center.y - c * inner));
        b.line_to(tip);
    });
    frame.stroke(
        &pointer,
        canvas::Stroke::default()
            .with_color(rgb(0xFF, 0x76, 0x7B))
            .with_width(2.5)
            .with_line_cap(canvas::LineCap::Round),
    );
    // Zero-length round-capped strokes in place of `frame.fill`-drawn dots —
    // plain fills silently fail to render anywhere in this board canvas's
    // cache-backed pipeline (reproduced with fills of every size/color, in
    // both the packed overlay frame and this isolated layer), while strokes
    // render reliably; a stroke this short with a round cap paints as a
    // filled disc of radius = width / 2.
    frame.stroke(
        &Path::line(tip, tip),
        canvas::Stroke::default()
            .with_color(rgb(0xFF, 0x76, 0x7B))
            .with_width(5.0)
            .with_line_cap(canvas::LineCap::Round),
    );
    frame.stroke(
        &Path::line(center, center),
        canvas::Stroke::default()
            .with_color(rgb(0x0B, 0x0B, 0x09))
            .with_width(radius * 0.18)
            .with_line_cap(canvas::LineCap::Round),
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_photographic_key_has_every_preprocessed_variant() {
        for key_id in 14..114 {
            for variant in 0..11 {
                let bytes = preprocessed_key_sprite(key_id, variant)
                    .expect("every non-knob key must have every visual variant");
                assert!(bytes.starts_with(b"RIFF"));
                assert_eq!(&bytes[8..12], b"WEBP");
            }
        }
    }

    #[test]
    fn every_drum_key_has_every_blank_cap_variant() {
        for key_id in 94..114 {
            for variant in 0..11 {
                let bytes = preprocessed_drum_key_sprite(key_id, variant)
                    .expect("every drum key must have every blank-cap variant");
                assert!(bytes.starts_with(b"RIFF"));
                assert_eq!(&bytes[8..12], b"WEBP");
            }
        }
        assert!(preprocessed_drum_key_sprite(93, 0).is_none());
        assert!(preprocessed_drum_key_sprite(114, 0).is_none());
    }

    #[test]
    fn annotated_middle_keys_recolor_their_left_bevel() {
        // One non-edge light key from each of the five alpha rows.
        for key_id in [17, 32, 46, 61, 74] {
            let resting = image::load_from_memory(
                preprocessed_key_sprite(key_id, 0).expect("resting sprite must exist"),
            )
            .expect("resting WebP must decode")
            .into_rgba8();
            let highlighted = image::load_from_memory(
                preprocessed_key_sprite(key_id, 9).expect("highlighted sprite must exist"),
            )
            .expect("highlighted WebP must decode")
            .into_rgba8();

            let left_bevel_width = (resting.width() / 5).max(1);
            let mut changed_material = 0_u32;
            let mut material_pixels = 0_u32;
            for y in 0..resting.height() {
                for x in 0..left_bevel_width {
                    let before = resting.get_pixel(x, y);
                    let brightness = (before[0] as f32 * 0.2126
                        + before[1] as f32 * 0.7152
                        + before[2] as f32 * 0.0722)
                        / 255.0;
                    if before[3] < 200 || brightness < 0.35 {
                        continue;
                    }
                    material_pixels += 1;
                    let after = highlighted.get_pixel(x, y);
                    let delta = (before[0] as i16 - after[0] as i16).unsigned_abs()
                        + (before[1] as i16 - after[1] as i16).unsigned_abs()
                        + (before[2] as i16 - after[2] as i16).unsigned_abs();
                    if delta > 30 {
                        changed_material += 1;
                    }
                }
            }

            assert!(
                material_pixels > 20,
                "key {key_id} needs sampled bevel material"
            );
            assert!(
                changed_material * 4 > material_pixels * 3,
                "key {key_id} left an unrecolored strip on its annotated bevel"
            );
        }
    }

    #[test]
    fn photo_key_geometry_scales_with_the_board() {
        let key = Key::new(1, "", 0.0, 1.0, Cluster::Alpha).size(1.5, 1.0);
        let large_size = Size::new(1484.0, 520.0);
        let small_size = Size::new(744.0, 260.0);
        let large = key_rect_with_size(&key, large_size, false);
        let small = key_rect_with_size(&key, small_size, false);

        let large_board = board_rect(large_size, false);
        let small_board = board_rect(small_size, false);
        let large_x = (large.x - large_board.x) / large_board.width;
        let small_x = (small.x - small_board.x) / small_board.width;
        assert!((large_x - small_x).abs() < 0.0001);
        assert!((large.width / large_board.width - small.width / small_board.width).abs() < 0.0001);
    }

    #[test]
    fn cropped_viewport_keeps_board_scale_and_removes_vertical_overflow() {
        let full_size = Size::new(1200.0, 600.0);
        let compact_size = Size::new(1200.0, 360.0);
        let full = board_rect(full_size, true);
        let compact = board_rect(compact_size, true);

        assert!((full.width - compact.width).abs() < 0.0001);
        assert!((full.height - compact.height).abs() < 0.0001);
        assert!(compact.y < 0.0);

        let available_width = 1196.0;
        let exact_crop_size = Size::new(
            1200.0,
            4.0 + available_width / COMPACT_CROP_WIDTH * COMPACT_CROP_HEIGHT,
        );
        let crop = photo_rect(
            exact_crop_size,
            true,
            COMPACT_CROP_X,
            COMPACT_CROP_Y,
            COMPACT_CROP_WIDTH,
            COMPACT_CROP_HEIGHT,
        );
        assert!((crop.x - 2.0).abs() < 0.0001);
        assert!((crop.y - 2.0).abs() < 0.0001);
        assert!((crop.width - available_width).abs() < 0.0001);
        assert!((crop.height - (exact_crop_size.height - 4.0)).abs() < 0.0001);
    }

    #[test]
    fn keyboard_resize_drag_is_clamped_in_both_directions() {
        assert_eq!(resized_keyboard_height(300.0, 40.0, 120.0, 500.0), 340.0);
        assert_eq!(resized_keyboard_height(300.0, -900.0, 120.0, 500.0), 120.0);
        assert_eq!(resized_keyboard_height(300.0, 900.0, 120.0, 500.0), 500.0);
    }

    #[test]
    fn keyboard_resize_handle_tracks_a_mouse_drag_outside_its_bounds() {
        let handle = BoardResizeHandle {
            current_height: 300.0,
            min_height: 120.0,
            max_height: 500.0,
        };
        let bounds = Rectangle {
            x: 10.0,
            y: 200.0,
            width: 800.0,
            height: 16.0,
        };
        let mut state = BoardResizeState::default();

        let pressed = <BoardResizeHandle as canvas::Program<Message>>::update(
            &handle,
            &mut state,
            &canvas::Event::Mouse(mouse::Event::ButtonPressed(mouse::Button::Left)),
            bounds,
            mouse::Cursor::Available(Point::new(400.0, 208.0)),
        );
        assert!(pressed.is_some());
        assert!(state.drag.is_some());

        let moved = <BoardResizeHandle as canvas::Program<Message>>::update(
            &handle,
            &mut state,
            &canvas::Event::Mouse(mouse::Event::CursorMoved {
                position: Point::new(400.0, 288.0),
            }),
            bounds,
            mouse::Cursor::Available(Point::new(400.0, 288.0)),
        )
        .expect("an active drag should publish the new keyboard height");
        let (message, _, _) = moved.into_inner();
        assert!(matches!(
            message,
            Some(Message::KeyboardHeightChanged(height)) if height == 380.0
        ));

        let released = <BoardResizeHandle as canvas::Program<Message>>::update(
            &handle,
            &mut state,
            &canvas::Event::Mouse(mouse::Event::ButtonReleased(mouse::Button::Left)),
            bounds,
            mouse::Cursor::Unavailable,
        );
        assert!(released.is_some());
        assert!(state.drag.is_none());
    }

    #[test]
    fn every_drum_pad_has_a_distinct_display_name() {
        let names: Vec<&str> = (36..=55).filter_map(drum_pad_name).collect();
        let distinct: HashSet<&str> = names.iter().copied().collect();

        assert_eq!(names.len(), 20);
        assert_eq!(distinct.len(), 20);
        assert_eq!(drum_pad_name(35), None);
        assert_eq!(drum_pad_name(56), None);
    }
}
