use std::cell::RefCell;
use std::collections::{HashMap, HashSet};

use iced::alignment::{Horizontal, Vertical};
use iced::widget::canvas::{self, Frame, Geometry, Path, Text};
use iced::{Color, Point, Rectangle, Renderer, Size, Theme, mouse};

use crate::key::{Cluster, Key, KeyId};
use crate::Message;

include!(concat!(env!("OUT_DIR"), "/k2_key_sprites.rs"));

/// Embedded photographic pieces of the real K2. Keeping the handles alive in
/// `App` lets iced cache the decoded shell PNGs and generated key WebPs instead
/// of allocating them on every frame.
pub struct PhotoBoardAssets {
    pub shell: iced::widget::image::Handle,
    pub leds: iced::widget::image::Handle,
    pub power_switch: iced::widget::image::Handle,
    pub display: iced::widget::image::Handle,
    key_sprites: RefCell<HashMap<(KeyId, u8), iced::widget::image::Handle>>,
}

impl PhotoBoardAssets {
    pub fn new() -> Self {
        let handle = |bytes: &'static [u8]| iced::widget::image::Handle::from_bytes(bytes);
        Self {
            shell: handle(&include_bytes!("../assets/keyboard/keyboard-clean-mask.png")[..]),
            leds: handle(&include_bytes!("../assets/keyboard/led-panel-board-crop.png")[..]),
            power_switch: handle(&include_bytes!("../assets/keyboard/power-switch.png")[..]),
            display: handle(&include_bytes!("../assets/keyboard/display.png")[..]),
            key_sprites: RefCell::new(HashMap::new()),
        }
    }

    /// Selects an already-isolated, already-colourized WebP generated by
    /// `build.rs`. Runtime work is limited to creating and caching the image
    /// handle; no flood fill or per-pixel colour math can interrupt playback.
    fn key_sprite(
        &self,
        key: &Key,
        lit_track: Option<usize>,
    ) -> Option<iced::widget::image::Handle> {
        let variant = match lit_track {
            None => 0,
            Some(value) if value == usize::MAX - 1 => 10,
            Some(usize::MAX) => 9,
            Some(track) => 1 + (track % TRACK_COLORS.len()) as u8,
        };
        if let Some(handle) = self.key_sprites.borrow().get(&(key.id, variant)).cloned() {
            return Some(handle);
        }
        let handle = iced::widget::image::Handle::from_bytes(
            preprocessed_key_sprite(key.id.0, variant)?,
        );
        self.key_sprites.borrow_mut().insert((key.id, variant), handle.clone());
        Some(handle)
    }
}

/// Per-track highlight palette — cycled for files with more than 8 tracks.
/// RGB values tuned for visibility on the dark PCB and dark staff background.
pub const TRACK_COLORS: &[(u8, u8, u8)] = &[
    (0x4F, 0xC3, 0xF7), // sky blue
    (0xFF, 0xB7, 0x4D), // amber
    (0xA5, 0xD6, 0xA7), // green
    (0xF4, 0x8F, 0xB1), // pink
    (0xCE, 0x93, 0xD8), // lavender
    (0xFF, 0xF1, 0x76), // yellow
    (0xFF, 0x8A, 0x65), // coral
    (0x80, 0xCB, 0xC4), // teal
];

pub(crate) const CANVAS_FONT: iced::Font = iced::Font::with_name("Fira Sans");
const TAPE_FONT: iced::Font = iced::Font::with_name("Permanent Marker");
#[cfg(test)]
const BASE_BOARD_HEIGHT: f32 = 520.0;

pub struct BoardCanvas<'a> {
    pub photo_assets: &'a PhotoBoardAssets,
    pub keys:        &'a [Key],
    /// Maps KeyId → track index for color. usize::MAX = manually toggled (uses original colour).
    pub highlighted: &'a HashMap<KeyId, usize>,
    /// Optional live overlay (for browser MIDI input) drawn above the base
    /// playback/selection highlight without requiring a temporary merged map.
    pub overlay_highlighted: Option<&'a HashMap<KeyId, usize>>,
    /// Chronological play steps to badge onto highlighted keys while a staff
    /// range is selected. Chords share a number; repeated keys have several.
    pub play_order:  Option<&'a HashMap<KeyId, Vec<usize>>>,
    /// Persistently-active control keys (e.g. layered waveform selects),
    /// independent of playback note overlays.
    pub selected_controls: &'a HashSet<KeyId>,
    /// Keys currently held with the pointer.
    pub pressed: &'a HashSet<KeyId>,
    /// Computer-key labels shown over the note names in performance mode.
    pub projected_labels: Option<&'a HashMap<KeyId, String>>,
    /// GM drum assignments for the numpad's 4x5 pad grid.
    pub drum_note_to_key: &'a HashMap<u8, KeyId>,
    /// Replace the numpad legends with instrument icons and names.
    pub show_drum_symbols: bool,
    /// Current 0.0..=1.0 dial position of each of the 12 encoder knobs.
    pub knob_values: &'a [f32],
}

#[derive(Default)]
pub struct CanvasState {
    photo_cache: canvas::Cache,
    overlay_cache: canvas::Cache,
    /// The knob drag popup gets its own geometry layer, separate from the
    /// crowded overlay frame — some large fills/thick strokes silently fail
    /// to render when they land late in a frame packed with hundreds of
    /// other draw calls (also seen on the numpad's drum-pad icons), and an
    /// isolated frame with far fewer prior draws reliably avoids it.
    slider_cache: canvas::Cache,
    /// Play-order badges get the same isolated-layer treatment as the knob
    /// slider popup — see `slider_cache`.
    badge_cache: canvas::Cache,
    pressed: Option<KeyId>,
    dragging_knob: Option<u8>,
    /// (cursor Y, knob value) captured on mouse-down, so dragging moves the
    /// value relative to where it already was instead of snapping it to
    /// whatever absolute position the click happened to land on — the knob
    /// itself sits above the pop-up track, so an absolute mapping always
    /// started the drag off the top or bottom of the track.
    drag_start: Option<(f32, f32)>,
}

/// Vertical extent of the pop-up slider shown while a knob is held, in
/// canvas-local coordinates. Cursor movement is mapped onto this range as a
/// delta from the drag's starting point (see `drag_start`), over a much
/// longer travel than the knob itself — far easier to land on a precise
/// setting than eyeballing rotation on a small dial.
fn knob_slider_track(knob_rect: Rectangle) -> (f32, f32) {
    let top = knob_rect.y + knob_rect.height + 22.0;
    (top, top + 160.0)
}

impl<'a> canvas::Program<Message> for BoardCanvas<'a> {
    type State = CanvasState;

    fn update(
        &self,
        state: &mut Self::State,
        event: &canvas::Event,
        bounds: Rectangle,
        cursor: mouse::Cursor,
    ) -> Option<canvas::Action<Message>> {
        match event {
            canvas::Event::Mouse(mouse::Event::ButtonPressed(mouse::Button::Left)) => {
                if let Some(pos) = cursor.position_in(bounds) {
                    for key in self.keys {
                        if key_rect_with_size(key, bounds.size()).contains(pos) {
                            if let Some(idx) = key.knob_index {
                                state.dragging_knob = Some(idx);
                                let current = self.knob_values.get(idx as usize).copied().unwrap_or(0.0);
                                // Anchor on the cursor's absolute (window) position, not the
                                // canvas-local one — `CursorMoved` below needs to keep tracking
                                // the drag even once the pointer leaves the canvas bounds
                                // (e.g. dragging a top-row knob upward past the board edge).
                                let start_y = cursor.position().map(|p| p.y).unwrap_or(pos.y);
                                state.drag_start = Some((start_y, current));
                                return Some(canvas::Action::capture());
                            }
                            state.pressed = Some(key.id);
                            return Some(
                                canvas::Action::publish(Message::KeyPressed(key.id))
                                    .and_capture(),
                            );
                        }
                    }
                }
            }
            canvas::Event::Mouse(mouse::Event::CursorMoved { .. }) => {
                if let Some(idx) = state.dragging_knob {
                    // Use the cursor's absolute position rather than
                    // `position_in(bounds)` — once the drag starts, the
                    // pointer is free to move outside the canvas (e.g.
                    // above a top-row knob) and should keep being tracked.
                    if let Some(pos) = cursor.position() {
                        if let Some(knob_rect) = self.keys.iter()
                            .find(|key| key.knob_index == Some(idx))
                            .map(|key| key_rect_with_size(key, bounds.size()))
                        {
                            let (top, bottom) = knob_slider_track(knob_rect);
                            let (start_y, start_value) = state.drag_start.unwrap_or((pos.y, 0.0));
                            let delta = (pos.y - start_y) / (bottom - top);
                            let value = (start_value - delta).clamp(0.0, 1.0);
                            return Some(
                                canvas::Action::publish(Message::KnobChanged(idx, value))
                                    .and_capture(),
                            );
                        }
                    }
                }
            }
            canvas::Event::Mouse(mouse::Event::ButtonReleased(mouse::Button::Left)) => {
                state.drag_start = None;
                if state.dragging_knob.take().is_some() {
                    return Some(canvas::Action::capture());
                }
                if let Some(id) = state.pressed.take() {
                    return Some(
                        canvas::Action::publish(Message::KeyReleased(id))
                            .and_capture(),
                    );
                }
            }
            // Hovering a knob and scrolling nudges its value — much easier
            // than dragging to "turn" it, which is what click-drag simulates.
            canvas::Event::Mouse(mouse::Event::WheelScrolled { delta }) => {
                if let Some(pos) = cursor.position_in(bounds) {
                    for key in self.keys {
                        if key_rect_with_size(key, bounds.size()).contains(pos) {
                            if let Some(idx) = key.knob_index {
                                let amount = match *delta {
                                    mouse::ScrollDelta::Lines { y, .. } => y * 0.05,
                                    mouse::ScrollDelta::Pixels { y, .. } => y / 200.0,
                                };
                                let current = self.knob_values.get(idx as usize).copied().unwrap_or(0.0);
                                let value = (current + amount).clamp(0.0, 1.0);
                                return Some(
                                    canvas::Action::publish(Message::KnobChanged(idx, value))
                                        .and_capture(),
                                );
                            }
                            break;
                        }
                    }
                }
            }
            _ => {}
        }
        None
    }

    fn draw(
        &self,
        state: &Self::State,
        renderer: &Renderer,
        _theme: &Theme,
        bounds: Rectangle,
        _cursor: mouse::Cursor,
    ) -> Vec<Geometry> {
        state.overlay_cache.clear(); // highlights can change every 16 ms during playback
        let active_knob = state.dragging_knob.map(|idx| {
            (idx, self.knob_values.get(idx as usize).copied().unwrap_or(0.0))
        });
        let photo_geometry = state.photo_cache.draw(renderer, bounds.size(), |frame| {
            draw_board_base(frame, self.photo_assets);
        });
        let mut badges: Vec<(Rectangle, Vec<usize>)> = Vec::new();
        let overlay_geometry = state.overlay_cache.draw(renderer, bounds.size(), |frame| {
            draw_board_overlay(
                frame,
                self.photo_assets,
                self.keys,
                self.highlighted,
                self.overlay_highlighted,
                self.play_order,
                self.selected_controls,
                self.pressed,
                self.projected_labels,
                self.drum_note_to_key,
                self.show_drum_symbols,
                self.knob_values,
                active_knob,
                &mut badges,
            );
        });
        // Keep interaction imagery separate from the cached photographic base
        // so active, colour-swapped key sprites render above the resting rows.
        let mut geometries = vec![photo_geometry, overlay_geometry];

        // The knob drag popup is its own isolated geometry — see the
        // `slider_cache` doc comment for why it can't just be the last thing
        // drawn into the (already large) overlay frame.
        if let Some((idx, value)) = active_knob {
            state.slider_cache.clear();
            let slider_geometry = state.slider_cache.draw(renderer, bounds.size(), |frame| {
                if let Some(knob_rect) = self.keys.iter()
                    .find(|key| key.knob_index == Some(idx))
                    .map(|key| key_rect_with_size(key, bounds.size()))
                {
                    draw_knob_slider(frame, knob_rect, value, knob_readout(idx, value));
                }
            });
            geometries.push(slider_geometry);
        }

        // Play-order badges also get their own isolated geometry — see the
        // `badge_cache` doc comment.
        if !badges.is_empty() {
            state.badge_cache.clear();
            let badge_geometry = state.badge_cache.draw(renderer, bounds.size(), |frame| {
                for (rect, steps) in &badges {
                    draw_play_order_badge(frame, *rect, steps);
                }
            });
            geometries.push(badge_geometry);
        }

        geometries
    }

    fn mouse_interaction(
        &self,
        state: &Self::State,
        bounds: Rectangle,
        cursor: mouse::Cursor,
    ) -> mouse::Interaction {
        if state.dragging_knob.is_some() {
            return mouse::Interaction::ResizingVertically;
        }
        if let Some(pos) = cursor.position_in(bounds) {
            for key in self.keys {
                if key_rect_with_size(key, bounds.size()).contains(pos) {
                    if key.is_knob {
                        return mouse::Interaction::ResizingVertically;
                    }
                    return mouse::Interaction::Pointer;
                }
            }
        }
        mouse::Interaction::default()
    }
}

#[cfg(test)]
pub fn key_rect(key: &Key) -> Rectangle {
    key_rect_with_size(key, Size::new(1484.0, BASE_BOARD_HEIGHT))
}

fn key_rect_with_size(key: &Key, size: Size) -> Rectangle {
    let canonical = match key.cluster {
        Cluster::Alpha | Cluster::AlphaLight => {
            let pitch = ALPHA_W / 15.0;
            Rectangle {
                x: ALPHA_X + key.col * pitch,
                y: ALPHA_Y + (key.row - 1.0) * ALPHA_ROW_PITCH,
                width: key.w * pitch,
                height: ALPHA_ROW_PITCH,
            }
        }
        Cluster::Nav => Rectangle {
            x: NAV_X + (key.col - 15.5) * (NAV_W / 3.0),
            y: NAV_Y + (key.row - 1.0) * (NAV_H / 2.0),
            width: key.w * (NAV_W / 3.0),
            height: key.h * (NAV_H / 2.0),
        },
        Cluster::Arrow => Rectangle {
            x: ARROW_X + (key.col - 15.5) * (ARROW_W / 3.0),
            y: ARROW_Y + (key.row - 4.0) * (ARROW_H / 2.0),
            width: key.w * (ARROW_W / 3.0),
            height: key.h * (ARROW_H / 2.0),
        },
        Cluster::Numpad => Rectangle {
            x: NUMPAD_X + (key.col - 19.0) * (NUMPAD_W / 4.0),
            y: NUMPAD_Y + key.row * (NUMPAD_H / 5.0),
            width: key.w * (NUMPAD_W / 4.0),
            height: key.h * (NUMPAD_H / 5.0),
        },
        Cluster::Encoder => {
            let index = key.knob_index.unwrap_or(12);
            if index == 12 {
                Rectangle { x: 102.0, y: 187.0, width: 100.0, height: 90.0 }
            } else {
                let group = (index / 4) as usize;
                let within = (index % 4) as f32;
                let banks: [(f32, f32, f32, f32); 3] = [
                    (260.0, 323.0, 190.0, 87.0),
                    (611.0, 309.0, 188.0, 91.0),
                    (947.0, 310.0, 188.0, 90.0),
                ];
                let (bank_x, bank_width, bank_y, bank_height) = banks[group];
                let segment = bank_width / 4.0;
                let diameter = bank_height.min(segment) * 0.68;
                Rectangle {
                    x: bank_x + (within + 0.5) * segment - diameter / 2.0,
                    y: bank_y + (bank_height - diameter) / 2.0,
                    width: diameter,
                    height: diameter,
                }
            }
        }
    };
    photo_rect(size, canonical.x, canonical.y, canonical.width, canonical.height)
}

fn key_sprite_rect_with_size(key: &Key, size: Size) -> Rectangle {
    let rect = key_rect_with_size(key, size);
    let source_aspect = match key.cluster {
        Cluster::Alpha | Cluster::AlphaLight => {
            let row = (key.row as usize).saturating_sub(1).min(4);
            let widths = [2129.0, 2119.0, 2114.0, 2128.0, 2131.0];
            let heights = [184.0, 180.0, 184.0, 184.0, 177.0];
            (widths[row] / 15.0 * key.w) / heights[row]
        }
        Cluster::Nav => (467.0 / 3.0 * key.w) / (308.0 / 2.0 * key.h),
        Cluster::Arrow => (456.0 / 3.0 * key.w) / (322.0 / 2.0 * key.h),
        Cluster::Numpad => (598.0 / 4.0 * key.w) / (738.0 / 5.0 * key.h),
        Cluster::Encoder => return rect,
    };
    Rectangle { height: rect.width / source_aspect, ..rect }
}

/// Returns (filter_color, text_color) for a key.
/// `lit_track`: Some(track) when playing, None when unlit.
fn key_colors(cluster: Cluster, lit_track: Option<usize>) -> (Color, Color) {
    let lit = lit_track.is_some();

    // For MIDI keys, use the track colour; fall back to gold for non-MIDI clusters.
    // usize::MAX - 1 = out-of-range warning (nearest key to a note off the board)
    if lit_track == Some(usize::MAX - 1) {
        let fill = rgb(0xFF, 0x3D, 0x72);
        return (fill, Color::WHITE);
    }

    let track_fill = |default_r, default_g, default_b| -> (Color, Color) {
        match lit_track {
            Some(t) if t != usize::MAX => {
                let (r, g, b) = TRACK_COLORS[t % TRACK_COLORS.len()];
                (Color::from_rgb8(r, g, b), Color::BLACK)
            }
            _ => (rgb(default_r, default_g, default_b), Color::BLACK),
        }
    };

    let (fill, text) = match (cluster, lit) {
        (Cluster::Alpha,      false) => (rgb(0x66, 0x75, 0x5E), Color::WHITE),
        (Cluster::Alpha,      true)  => track_fill(0xFF, 0xA3, 0x55),
        (Cluster::AlphaLight, false) => (rgb(0xDF, 0xE3, 0xD2), Color::BLACK),
        (Cluster::AlphaLight, true)  => track_fill(0xFF, 0xA3, 0x55),
        (Cluster::Nav,        false) => (rgb(0xC9, 0xC6, 0xBA), Color::BLACK),
        (Cluster::Nav,        true)  => (rgb(0xFF, 0xB4, 0x58), Color::BLACK),
        (Cluster::Arrow,      false) => (rgb(0xCF, 0x7F, 0x6C), Color::BLACK),
        (Cluster::Arrow,      true)  => (rgb(0xFF, 0x4C, 0x82), Color::WHITE),
        (Cluster::Numpad,     false) => (rgb(0xD9, 0xD4, 0xC8), Color::BLACK),
        (Cluster::Numpad,     true)  => (rgb(0x50, 0xD4, 0xC8), Color::BLACK),
        (Cluster::Encoder,    _)     => (rgb(0x1D, 0x1B, 0x28), Color::WHITE),
    };

    (fill, text)
}

fn rgb(r: u8, g: u8, b: u8) -> Color {
    Color::from_rgb8(r, g, b)
}

const PHOTO_WIDTH: f32 = 1949.0;
const PHOTO_HEIGHT: f32 = 807.0;
const ALPHA_X: f32 = 124.0;
const ALPHA_Y: f32 = 346.0;
const ALPHA_W: f32 = 1129.0;
const ALPHA_H: f32 = 383.0;
const ALPHA_ROW_PITCH: f32 = 72.3;
const NAV_X: f32 = 1276.0;
const NAV_Y: f32 = 348.0;
const NAV_W: f32 = 228.0;
const NAV_H: f32 = 156.0;
const ARROW_X: f32 = 1278.0;
const ARROW_Y: f32 = 581.0;
const ARROW_W: f32 = 223.0;
const ARROW_H: f32 = 147.0;
const NUMPAD_X: f32 = 1534.0;
const NUMPAD_Y: f32 = 347.0;
const NUMPAD_W: f32 = 296.0;
const NUMPAD_H: f32 = 382.0;

fn board_rect(size: Size) -> Rectangle {
    let available = Rectangle {
        x: 2.0,
        y: 2.0,
        width: (size.width - 4.0).max(1.0),
        height: (size.height - 4.0).max(1.0),
    };
    let scale = (available.width / PHOTO_WIDTH)
        .min(available.height / PHOTO_HEIGHT)
        .max(0.0001);
    let width = PHOTO_WIDTH * scale;
    let height = PHOTO_HEIGHT * scale;
    Rectangle {
        x: available.x + (available.width - width) / 2.0,
        y: available.y + (available.height - height) / 2.0,
        width,
        height,
    }
}

fn photo_rect(size: Size, x: f32, y: f32, width: f32, height: f32) -> Rectangle {
    let board = board_rect(size);
    Rectangle {
        x: board.x + x / PHOTO_WIDTH * board.width,
        y: board.y + y / PHOTO_HEIGHT * board.height,
        width: width / PHOTO_WIDTH * board.width,
        height: height / PHOTO_HEIGHT * board.height,
    }
}

#[derive(Clone, Copy)]
struct TapeLabel {
    text: &'static str,
    x: f32,
    y: f32,
    size: f32,
}

fn draw_tape_labels(frame: &mut Frame, size: Size) {
    let board = board_rect(size);
    let scale = board.width / PHOTO_WIDTH;
    let ink = Color::from_rgba8(0x20, 0x2A, 0x2D, 0.88);
    let labels = [
        TapeLabel { text: "ON/OFF", x: 151.0, y: 132.0, size: 20.0 },
        TapeLabel { text: "VOL", x: 300.0, y: 132.0, size: 15.0 },
        TapeLabel { text: "CUTOFF", x: 381.0, y: 132.0, size: 13.0 },
        TapeLabel { text: "ATTACK", x: 462.0, y: 132.0, size: 13.0 },
        TapeLabel { text: "RELEASE", x: 543.0, y: 132.0, size: 12.0 },
        TapeLabel { text: "DECAY", x: 650.0, y: 132.0, size: 13.0 },
        TapeLabel { text: "SUSTAIN", x: 727.0, y: 132.0, size: 12.0 },
        TapeLabel { text: "DRUM\nVOL", x: 804.0, y: 132.0, size: 11.0 },
        TapeLabel { text: "PAN", x: 881.0, y: 132.0, size: 14.0 },
        TapeLabel { text: "VIB RATE", x: 986.0, y: 132.0, size: 11.0 },
        TapeLabel { text: "VIB DEPTH", x: 1063.0, y: 132.0, size: 10.5 },
        TapeLabel { text: "TREMOLO", x: 1141.0, y: 132.0, size: 11.0 },
        TapeLabel { text: "GLIDE", x: 1218.0, y: 132.0, size: 13.0 },
        TapeLabel { text: "MIDI\nSEND", x: 1594.0, y: 132.0, size: 13.0 },
        TapeLabel { text: "MIDI\nRECV", x: 1695.0, y: 132.0, size: 13.0 },
        TapeLabel { text: "STATUS", x: 1798.0, y: 132.0, size: 13.0 },
        TapeLabel { text: "HALL EFFECT SWITCHES  /  VELOCITY MEMORY", x: 751.0, y: 313.0, size: 11.0 },
        TapeLabel { text: "TRI", x: 1314.0, y: 313.0, size: 17.0 },
        TapeLabel { text: "SQR", x: 1390.0, y: 313.0, size: 17.0 },
        TapeLabel { text: "SAW", x: 1466.0, y: 313.0, size: 17.0 },
        TapeLabel { text: "SIN", x: 1314.0, y: 542.0, size: 17.0 },
        TapeLabel { text: "PULSE", x: 1390.0, y: 542.0, size: 13.0 },
        TapeLabel { text: "NOISE", x: 1466.0, y: 542.0, size: 13.0 },
        TapeLabel { text: "WICKI–HAYDEN  NOTE  LAYOUT", x: 715.0, y: 774.0, size: 18.0 },
        TapeLabel { text: "MIDI\nPITCH\nDOWN", x: 1320.0, y: 770.0, size: 11.0 },
        TapeLabel { text: "MIDI\nPITCH\nUP", x: 1454.0, y: 770.0, size: 11.0 },
        TapeLabel { text: "DRUMS", x: 1690.0, y: 770.0, size: 20.0 },
    ];

    for label in labels {
        let point = Point::new(
            board.x + label.x * scale,
            board.y + label.y * scale,
        );
        frame.fill_text(Text {
            content: label.text.to_string(),
            position: point,
            color: ink,
            size: iced::Pixels((label.size * scale).max(4.0)),
            font: TAPE_FONT,
            align_x: Horizontal::Center.into(),
            align_y: Vertical::Center,
            ..Text::default()
        });
    }

    frame.fill_text(Text {
        content: "THE\nKEYBOARD²".to_string(),
        position: Point::new(board.x + 55.0 * scale, board.y + 525.0 * scale),
        color: ink,
        size: iced::Pixels((12.0 * scale).max(4.0)),
        font: TAPE_FONT,
        align_x: Horizontal::Center.into(),
        align_y: Vertical::Center,
        ..Text::default()
    });
}

fn contained_rect(target: Rectangle, source_width: f32, source_height: f32) -> Rectangle {
    let scale = (target.width / source_width).min(target.height / source_height);
    let width = source_width * scale;
    let height = source_height * scale;
    Rectangle {
        x: target.x + (target.width - width) / 2.0,
        y: target.y + (target.height - height) / 2.0,
        width,
        height,
    }
}

fn draw_board_base(frame: &mut Frame, photo_assets: &PhotoBoardAssets) {
    let size = frame.size();
    let board = board_rect(size);

    frame.fill(&Path::rectangle(Point::ORIGIN, size), rgb(0x09, 0x0D, 0x0E));
    let shadow = rounded_rect(
        Rectangle { x: board.x + 3.0, y: board.y + 7.0, ..board },
        14.0,
    );
    frame.fill(&shadow, Color::from_rgba8(0, 0, 0, 0.62));

    for (x, y, width, height) in [
        (102.0, 187.0, 100.0, 90.0),
        (260.0, 190.0, 323.0, 87.0),
        (611.0, 188.0, 309.0, 91.0),
        (947.0, 188.0, 310.0, 90.0),
        (1282.0, 187.0, 233.0, 90.0),
        (1543.0, 189.0, 305.0, 89.0),
        (ALPHA_X, ALPHA_Y, ALPHA_W, ALPHA_H),
        (NAV_X, NAV_Y, NAV_W, NAV_H),
        (ARROW_X, ARROW_Y, ARROW_W, ARROW_H),
        (NUMPAD_X, NUMPAD_Y, NUMPAD_W, NUMPAD_H),
    ] {
        let rect = photo_rect(size, x, y, width, height);
        frame.fill(
            &Path::rectangle(Point::new(rect.x, rect.y), rect.size()),
            rgb(0x07, 0x09, 0x08),
        );
    }

    frame.draw_image(board, &photo_assets.shell);
    frame.draw_image(
        contained_rect(photo_rect(size, 102.0, 187.0, 100.0, 90.0), 192.0, 184.0),
        &photo_assets.power_switch,
    );
    frame.draw_image(
        contained_rect(photo_rect(size, 1282.0, 187.0, 233.0, 90.0), 447.0, 178.0),
        &photo_assets.display,
    );
    frame.draw_image(
        contained_rect(photo_rect(size, 1543.0, 189.0, 305.0, 89.0), 577.0, 175.0),
        &photo_assets.leds,
    );
}

fn draw_board_overlay(
    frame: &mut Frame,
    photo_assets: &PhotoBoardAssets,
    keys: &[Key],
    highlighted: &HashMap<KeyId, usize>,
    overlay_highlighted: Option<&HashMap<KeyId, usize>>,
    play_order: Option<&HashMap<KeyId, Vec<usize>>>,
    selected_controls: &HashSet<KeyId>,
    pressed: &HashSet<KeyId>,
    projected_labels: Option<&HashMap<KeyId, String>>,
    drum_note_to_key: &HashMap<u8, KeyId>,
    show_drum_symbols: bool,
    knob_values: &[f32],
    active_knob: Option<(u8, f32)>,
    badges: &mut Vec<(Rectangle, Vec<usize>)>,
) {
    let size = frame.size();
    let display_bezel_rect = photo_rect(size, 1282.0, 187.0, 233.0, 90.0);
    let display_text = active_knob
        .and_then(|(idx, value)| knob_readout(idx, value))
        .unwrap_or_else(|| "MIDI READY".to_string());
    frame.fill_text(Text {
        content: display_text,
        position: Point::new(
            display_bezel_rect.x + display_bezel_rect.width / 2.0,
            display_bezel_rect.y + display_bezel_rect.height / 2.0,
        ),
        color: rgb(0xFF, 0xB5, 0x58),
        size: iced::Pixels((board_rect(size).width / PHOTO_WIDTH * 14.0).clamp(7.0, 14.0)),
        font: CANVAS_FONT,
        align_x: Horizontal::Center.into(),
        align_y: Vertical::Center,
        ..Text::default()
    });

    draw_tape_labels(frame, size);

    for key in keys {
        let rect = key_rect_with_size(key, size);
        let lit_track = overlay_highlighted.and_then(|overlay| overlay.get(&key.id)).copied()
            .or_else(|| highlighted.get(&key.id).copied())
            .or_else(|| {
                (selected_controls.contains(&key.id) || pressed.contains(&key.id))
                    .then_some(usize::MAX)
            });

        if key.is_knob {
            let value = key.knob_index
                .and_then(|idx| knob_values.get(idx as usize))
                .copied()
                .unwrap_or(0.0);
            let label = key.knob_index
                .and_then(|idx| crate::synth::KNOB_PARAMS.get(idx as usize))
                .map(|param| param.label);
            draw_knob(frame, rect, value, label);
            continue;
        }

        let (_, text_color) = key_colors(key.cluster, lit_track);
        let press_offset = lit_track
            .map(|_| (rect.height * 0.055).clamp(1.0, 4.0))
            .unwrap_or(0.0);
        let mut sprite_rect = key_sprite_rect_with_size(key, size);
        sprite_rect.y += press_offset;
        if let Some(sprite) = photo_assets.key_sprite(key, lit_track) {
            frame.draw_image(sprite_rect, &sprite);
        }
        let visual_rect = Rectangle { y: rect.y + press_offset, ..rect };

        let drum_note = show_drum_symbols
            .then(|| {
                drum_note_to_key.iter()
                    .find_map(|(&note, &id)| (id == key.id).then_some(note))
            })
            .flatten();
        let projected_label = projected_labels.and_then(|labels| labels.get(&key.id));

        if let Some(note) = drum_note {
            draw_drum_symbol(
                frame,
                visual_rect,
                note,
                text_color,
                projected_label.map(String::as_str),
            );
            if let Some(steps) = play_order.and_then(|order| order.get(&key.id)) {
                badges.push((visual_rect, steps.clone()));
            }
            continue;
        }

        let (primary_label, secondary_label) = match key.cluster {
            Cluster::Alpha | Cluster::AlphaLight => (
                projected_label.map(String::as_str).unwrap_or(key.label),
                if projected_label.is_some() { Some(key.label) } else { None },
            ),
            Cluster::Nav | Cluster::Arrow => (
                projected_label.map(String::as_str).unwrap_or(""),
                None,
            ),
            // The numpad's computer-key labels only ever add information as
            // the small corner hint drawn by `draw_drum_symbol` above, once
            // drum symbols replace its photographed digits. Outside that
            // mode the real photographed numpad already shows the same
            // digit, so drawing it again here would just double it.
            Cluster::Numpad => ("", None),
            Cluster::Encoder => unreachable!(),
        };

        if !primary_label.is_empty() {
            frame.fill_text(Text {
                content: primary_label.to_string(),
                position: Point::new(
                    visual_rect.x + visual_rect.width / 2.0,
                    visual_rect.y + visual_rect.height / 2.0
                        - if secondary_label.is_some() { 6.0 } else { 0.0 },
                ),
                color: text_color,
                size: iced::Pixels(if primary_label.len() > 4 { 11.0 } else { 14.0 }),
                font: CANVAS_FONT,
                align_x: Horizontal::Center.into(),
                align_y: Vertical::Center,
                ..Text::default()
            });
        }

        if let Some(sub) = secondary_label {
            frame.fill_text(Text {
                content: sub.to_string(),
                position: Point::new(
                    visual_rect.x + visual_rect.width / 2.0,
                    visual_rect.y + visual_rect.height / 2.0 + 12.0,
                ),
                color: Color::from_rgba8(0, 0, 0, 0.6),
                size: iced::Pixels(10.0),
                font: CANVAS_FONT,
                align_x: Horizontal::Center.into(),
                align_y: Vertical::Center,
                ..Text::default()
            });
        }

        if let Some(steps) = play_order.and_then(|order| order.get(&key.id)) {
            badges.push((visual_rect, steps.clone()));
        }
    }
}

fn drum_pad_name(note: u8) -> Option<&'static str> {
    Some(match note {
        36 => "KICK",
        37 => "STICK",
        38 => "SNARE",
        39 => "CLAP",
        40 => "E.SNARE",
        41 => "LO FLOOR",
        42 => "CLOSED HH",
        43 => "HI FLOOR",
        44 => "PEDAL HH",
        45 => "LOW TOM",
        46 => "OPEN HH",
        47 => "LO-MID",
        48 => "HI-MID",
        49 => "CRASH",
        50 => "HIGH TOM",
        51 => "RIDE",
        52 => "CHINA",
        53 => "RIDE BELL",
        54 => "TAMBO",
        55 => "SPLASH",
        _ => return None,
    })
}

fn icon_line(frame: &mut Frame, from: Point, to: Point, color: Color, width: f32) {
    frame.stroke(
        &Path::line(from, to),
        canvas::Stroke::default().with_color(color).with_width(width),
    );
}

fn draw_drum_body(frame: &mut Frame, center: Point, color: Color, floor_legs: bool) {
    let body = rounded_rect(
        Rectangle { x: center.x - 9.0, y: center.y - 6.0, width: 18.0, height: 12.0 },
        3.0,
    );
    frame.stroke(
        &body,
        canvas::Stroke::default().with_color(color).with_width(1.7),
    );
    icon_line(
        frame,
        Point::new(center.x - 8.0, center.y - 2.0),
        Point::new(center.x + 8.0, center.y - 2.0),
        color,
        1.2,
    );
    if floor_legs {
        icon_line(frame, Point::new(center.x - 6.0, center.y + 6.0), Point::new(center.x - 8.0, center.y + 10.0), color, 1.5);
        icon_line(frame, Point::new(center.x + 6.0, center.y + 6.0), Point::new(center.x + 8.0, center.y + 10.0), color, 1.5);
    }
}

fn draw_hi_hat(frame: &mut Frame, center: Point, color: Color, open: bool, pedal: bool) {
    let spread = if open { 3.5 } else { 1.5 };
    icon_line(frame, Point::new(center.x - 9.0, center.y - spread), Point::new(center.x + 9.0, center.y - spread), color, 1.7);
    icon_line(frame, Point::new(center.x - 9.0, center.y + spread), Point::new(center.x + 9.0, center.y + spread), color, 1.7);
    icon_line(frame, Point::new(center.x, center.y + spread), Point::new(center.x, center.y + 10.0), color, 1.4);
    icon_line(frame, Point::new(center.x - 6.0, center.y + 10.0), Point::new(center.x + 6.0, center.y + 10.0), color, 1.4);
    if pedal {
        icon_line(frame, Point::new(center.x, center.y + 7.0), Point::new(center.x + 8.0, center.y + 10.0), color, 1.5);
    }
}

fn draw_cymbal(frame: &mut Frame, center: Point, color: Color, small: bool) {
    let half_width = if small { 7.0 } else { 11.0 };
    let cymbal = Path::new(|b| {
        b.move_to(Point::new(center.x - half_width, center.y));
        b.quadratic_curve_to(
            Point::new(center.x, center.y - 4.0),
            Point::new(center.x + half_width, center.y),
        );
    });
    frame.stroke(
        &cymbal,
        canvas::Stroke::default().with_color(color).with_width(1.8),
    );
    frame.fill(&Path::circle(Point::new(center.x, center.y - 2.0), 2.0), color);
    icon_line(frame, Point::new(center.x, center.y), Point::new(center.x, center.y + 10.0), color, 1.4);
    icon_line(frame, Point::new(center.x - 5.0, center.y + 10.0), Point::new(center.x + 5.0, center.y + 10.0), color, 1.4);
}

/// Draw a small pictogram plus a compact GM instrument name. The text keeps
/// closely-related toms and cymbals unambiguous, while the shapes remain easy
/// to scan during performance.
fn draw_drum_symbol(
    frame: &mut Frame,
    rect: Rectangle,
    note: u8,
    color: Color,
    computer_key: Option<&str>,
) {
    let Some(name) = drum_pad_name(note) else { return };
    // The numpad row's real photographed key face only fills roughly the
    // bottom 80% of its cell (the top is the switch-well shadow), so a fixed
    // pixel offset from the cell top can land in that shadow instead of on
    // the cap. Anchor both the icon and the name proportionally within the
    // cell so they land on the visible cap at any window size.
    let cap_top = rect.y + rect.height * 0.22;
    let center = Point::new(rect.x + rect.width / 2.0, cap_top + rect.height * 0.20);

    match note {
        36 => {
            let drum = Path::circle(center, 9.0);
            frame.stroke(&drum, canvas::Stroke::default().with_color(color).with_width(1.8));
            frame.fill(&Path::circle(center, 2.2), color);
            icon_line(frame, Point::new(center.x - 6.0, center.y + 7.0), Point::new(center.x - 9.0, center.y + 11.0), color, 1.4);
            icon_line(frame, Point::new(center.x + 6.0, center.y + 7.0), Point::new(center.x + 9.0, center.y + 11.0), color, 1.4);
        }
        37 => {
            icon_line(frame, Point::new(center.x - 8.0, center.y + 8.0), Point::new(center.x + 8.0, center.y - 8.0), color, 2.2);
            icon_line(frame, Point::new(center.x - 8.0, center.y - 8.0), Point::new(center.x + 8.0, center.y + 8.0), color, 2.2);
            frame.fill(&Path::circle(Point::new(center.x - 8.0, center.y + 8.0), 1.8), color);
            frame.fill(&Path::circle(Point::new(center.x + 8.0, center.y + 8.0), 1.8), color);
        }
        38 | 40 => {
            draw_drum_body(frame, center, color, false);
            if note == 40 {
                let bolt = Path::new(|b| {
                    b.move_to(Point::new(center.x + 1.0, center.y - 8.0));
                    b.line_to(Point::new(center.x - 2.0, center.y - 1.0));
                    b.line_to(Point::new(center.x + 2.0, center.y - 1.0));
                    b.line_to(Point::new(center.x - 1.0, center.y + 7.0));
                });
                frame.stroke(&bolt, canvas::Stroke::default().with_color(color).with_width(1.4));
            }
        }
        39 => {
            let hand = rounded_rect(
                Rectangle { x: center.x - 6.0, y: center.y - 1.0, width: 12.0, height: 10.0 },
                3.0,
            );
            frame.stroke(&hand, canvas::Stroke::default().with_color(color).with_width(1.5));
            for offset in [-6.0, -2.0, 2.0, 6.0] {
                icon_line(frame, Point::new(center.x + offset, center.y - 1.0), Point::new(center.x + offset, center.y - 9.0 + offset.abs() * 0.25), color, 1.5);
            }
        }
        41 | 43 => {
            draw_drum_body(frame, center, color, true);
            let dot_y = if note == 41 { center.y + 2.0 } else { center.y - 4.0 };
            frame.fill(&Path::circle(Point::new(center.x, dot_y), 1.8), color);
        }
        42 => draw_hi_hat(frame, center, color, false, false),
        44 => draw_hi_hat(frame, center, color, false, true),
        46 => draw_hi_hat(frame, center, color, true, false),
        45 | 47 | 48 | 50 => {
            draw_drum_body(frame, center, color, false);
            let dot_y = match note {
                45 => center.y + 3.0,
                47 => center.y + 1.0,
                48 => center.y - 2.0,
                _ => center.y - 4.0,
            };
            frame.fill(&Path::circle(Point::new(center.x, dot_y), 1.8), color);
        }
        49 => {
            draw_cymbal(frame, center, color, false);
            for (dx, dy) in [(-12.0, -5.0), (12.0, -5.0), (0.0, -11.0)] {
                icon_line(frame, Point::new(center.x + dx * 0.72, center.y + dy * 0.72), Point::new(center.x + dx, center.y + dy), color, 1.2);
            }
        }
        51 => draw_cymbal(frame, center, color, false),
        52 => {
            let china = Path::new(|b| {
                b.move_to(Point::new(center.x - 11.0, center.y - 3.0));
                b.quadratic_curve_to(Point::new(center.x, center.y + 5.0), Point::new(center.x + 11.0, center.y - 3.0));
            });
            frame.stroke(&china, canvas::Stroke::default().with_color(color).with_width(1.8));
            frame.fill(&Path::circle(Point::new(center.x, center.y), 2.0), color);
            icon_line(frame, Point::new(center.x, center.y + 1.0), Point::new(center.x, center.y + 10.0), color, 1.4);
        }
        53 => {
            let bell = Path::new(|b| {
                b.move_to(Point::new(center.x - 8.0, center.y + 6.0));
                b.quadratic_curve_to(Point::new(center.x - 5.0, center.y - 7.0), Point::new(center.x, center.y - 8.0));
                b.quadratic_curve_to(Point::new(center.x + 5.0, center.y - 7.0), Point::new(center.x + 8.0, center.y + 6.0));
                b.line_to(Point::new(center.x - 8.0, center.y + 6.0));
            });
            frame.stroke(&bell, canvas::Stroke::default().with_color(color).with_width(1.7));
            frame.fill(&Path::circle(Point::new(center.x, center.y + 8.0), 2.0), color);
        }
        54 => {
            let ring = Path::circle(center, 8.0);
            frame.stroke(&ring, canvas::Stroke::default().with_color(color).with_width(1.8));
            for (dx, dy) in [(0.0, -10.0), (9.0, -4.0), (9.0, 4.0), (0.0, 10.0), (-9.0, 4.0), (-9.0, -4.0)] {
                frame.fill(&Path::circle(Point::new(center.x + dx, center.y + dy), 1.7), color);
            }
        }
        55 => {
            draw_cymbal(frame, center, color, true);
            for (dx, dy) in [(-9.0, -7.0), (0.0, -11.0), (9.0, -7.0)] {
                icon_line(frame, Point::new(center.x + dx * 0.7, center.y + dy * 0.7), Point::new(center.x + dx, center.y + dy), color, 1.2);
            }
        }
        _ => {}
    }

    if let Some(key) = computer_key {
        frame.fill_text(Text {
            content: key.to_string(),
            position: Point::new(rect.x + 5.0, cap_top + 4.0),
            color: Color { a: 0.58, ..color },
            size: iced::Pixels(7.0),
            font: CANVAS_FONT,
            align_x: Horizontal::Left.into(),
            ..Text::default()
        });
    }

    frame.fill_text(Text {
        content: name.to_string(),
        position: Point::new(rect.x + rect.width / 2.0, rect.y + rect.height * 0.90),
        color,
        size: iced::Pixels(if name.len() > 8 { 7.0 } else { 8.0 }),
        font: CANVAS_FONT,
        align_x: Horizontal::Center.into(),
        align_y: Vertical::Center,
        ..Text::default()
    });
}

/// Draws a compact, high-contrast sequence badge in the key's upper-right
/// corner. A repeated key reads e.g. "2·5"; simultaneous chord keys all show
/// the same number.
fn draw_play_order_badge(frame: &mut Frame, key_rect: Rectangle, steps: &[usize]) {
    if steps.is_empty() { return; }

    let label = steps
        .iter()
        .map(usize::to_string)
        .collect::<Vec<_>>()
        .join("·");
    let char_count = label.chars().count().max(1) as f32;
    let width = (char_count * 6.0 + 10.0).clamp(18.0, key_rect.width - 8.0);
    let height: f32 = 18.0;
    let badge = Rectangle {
        x: key_rect.x + key_rect.width - width - 4.0,
        y: key_rect.y + 4.0,
        width,
        height: height.min(key_rect.height - 8.0),
    };
    let path = Path::rectangle(Point::new(badge.x, badge.y), badge.size());
    frame.fill(&path, Color::from_rgba8(0x2A, 0x25, 0x20, 0.92));
    frame.stroke(
        &path,
        canvas::Stroke::default()
            .with_color(Color::from_rgba8(0xFF, 0xFF, 0xFF, 0.78))
            .with_width(1.0),
    );

    // Long repeated-note sequences shrink to stay inside their key rather
    // than spilling across adjacent labels.
    let font_size = (width / (char_count * 0.62)).clamp(6.0, 10.0);
    frame.fill_text(Text {
        content: label,
        position: Point::new(badge.x + badge.width / 2.0, badge.y + badge.height / 2.0),
        color: Color::WHITE,
        size: iced::Pixels(font_size),
        font: CANVAS_FONT,
        align_x: Horizontal::Center.into(),
        align_y: Vertical::Center,
        ..Text::default()
    });
}

/// Formats a knob's current position as "<label> <real value>" (e.g.
/// "Volume 1.00"), scaling the normalized 0.0..=1.0 dial position into the
/// parameter's real engine units via `KNOB_PARAMS`.
fn knob_readout(idx: u8, value: f32) -> Option<String> {
    crate::synth::KNOB_PARAMS.get(idx as usize).map(|param| {
        let real = param.min + value.clamp(0.0, 1.0) * (param.max - param.min);
        format!("{} {:.2}", param.label, real)
    })
}

fn draw_knob_slider(frame: &mut Frame, knob_rect: Rectangle, value: f32, readout: Option<String>) {
    let (top, bottom) = knob_slider_track(knob_rect);
    let center_x = knob_rect.x + knob_rect.width / 2.0;
    let value = value.clamp(0.0, 1.0);
    // Panel width must track the readout text ("Vib Depth 50.00" is the
    // longest label+value pair) — a fixed width let long labels overflow
    // the opaque background onto the keys behind, making them unreadable.
    let panel_width = readout
        .as_ref()
        .map(|text| (text.len() as f32 * 7.2 + 28.0).max(100.0))
        .unwrap_or(100.0);

    let panel = rounded_rect(
        Rectangle {
            x: center_x - panel_width / 2.0,
            y: top - 30.0,
            width: panel_width,
            height: (bottom - top) + 40.0,
        },
        8.0,
    );
    // Very dark, low-RGB fill colors (roughly below 0x20 per channel) render
    // as invisible or badly washed out in this app's canvas pipeline even at
    // full alpha, while otherwise-identical strokes render correctly — this
    // panel used to be near-black (0x11,0x13,0x0F) and never appeared at
    // all. Kept dark but nudged into a range that actually paints.
    frame.fill(&panel, Color::from_rgba8(0x20, 0x1E, 0x2A, 0.97));
    frame.stroke(
        &panel,
        canvas::Stroke::default().with_color(rgb(0x75, 0x6B, 0x4E)).with_width(1.0),
    );

    if let Some(readout) = readout {
        frame.fill_text(Text {
            content: readout,
            position: Point::new(center_x, top - 14.0),
            color: rgb(0xFF, 0xD3, 0x9B),
            size: iced::Pixels(12.0),
            font: CANVAS_FONT,
            align_x: Horizontal::Center.into(),
            align_y: Vertical::Center,
            ..Text::default()
        });
    }

    let track = rounded_rect(
        Rectangle { x: center_x - 3.0, y: top, width: 6.0, height: bottom - top },
        3.0,
    );
    frame.fill(&track, rgb(0x25, 0x27, 0x1D));

    let handle_y = top + (1.0 - value) * (bottom - top);
    let filled = rounded_rect(
        Rectangle { x: center_x - 3.0, y: handle_y, width: 6.0, height: bottom - handle_y },
        3.0,
    );
    frame.fill(&filled, rgb(0xFF, 0x76, 0x7B));

    let handle = Path::circle(Point::new(center_x, handle_y), 8.0);
    frame.fill(&handle, rgb(0xFF, 0x76, 0x7B));
    frame.stroke(&handle, canvas::Stroke::default().with_color(Color::WHITE).with_width(1.5));
}

fn rounded_rect(rect: Rectangle, radius: f32) -> Path {
    Path::new(|builder| {
        builder.rounded_rectangle(
            Point::new(rect.x, rect.y),
            Size::new(rect.width, rect.height),
            radius.into(),
        );
    })
}

fn draw_knob(frame: &mut Frame, rect: Rectangle, value: f32, label: Option<&str>) {
    let center = Point::new(rect.x + rect.width / 2.0, rect.y + rect.height / 2.0);
    let radius = rect.width.min(rect.height) / 2.0 - 4.0;

    frame.fill(
        &Path::circle(Point::new(center.x, center.y + 3.0), radius + 1.0),
        Color::from_rgba8(0, 0, 0, 0.45),
    );

    let base = Path::circle(center, radius);
    frame.fill(&base, rgb(0x13, 0x12, 0x1C));
    frame.stroke(
        &base,
        canvas::Stroke::default().with_color(rgb(0x6A, 0x60, 0x48)).with_width(1.0),
    );

    let knurl = Path::circle(center, radius * 0.55);
    frame.fill(&knurl, rgb(0x25, 0x27, 0x1D));

    // Sweeps -135°..+135° (bottom-left to bottom-right through the top) as
    // `value` goes 0.0..=1.0, mirroring a real knob's travel.
    let angle = -135f32.to_radians() + value.clamp(0.0, 1.0) * 270f32.to_radians();
    let (s, c) = (angle.sin(), angle.cos());
    let inner = radius * 0.35;
    let outer = radius * 0.85;
    let tip = Point::new(center.x + s * outer, center.y - c * outer);
    let pointer = Path::new(|b| {
        b.move_to(Point::new(center.x + s * inner, center.y - c * inner));
        b.line_to(tip);
    });
    frame.stroke(
        &pointer,
        canvas::Stroke::default().with_color(rgb(0xFF, 0x76, 0x7B)).with_width(2.5),
    );
    frame.fill(&Path::circle(tip, 2.5), rgb(0xFF, 0x76, 0x7B));

    if let Some(label) = label {
        let label_size = (rect.width * 0.16).clamp(4.0, 8.0);
        frame.fill_text(Text {
            content: label.to_string(),
            position: Point::new(center.x, rect.y + rect.height + label_size + 1.0),
            color: rgb(0xB8, 0xAD, 0x8E),
            size: iced::Pixels(label_size),
            font: CANVAS_FONT,
            align_x: Horizontal::Center.into(),
            align_y: Vertical::Center,
            ..Text::default()
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_photographic_key_has_every_preprocessed_variant() {
        for key_id in 14..114 {
            for variant in 0..11 {
                let bytes = preprocessed_key_sprite(key_id, variant)
                    .expect("every non-knob key must have every visual variant");
                assert!(bytes.starts_with(b"RIFF"));
                assert_eq!(&bytes[8..12], b"WEBP");
            }
        }
    }

    #[test]
    fn photo_key_geometry_scales_with_the_board() {
        let key = Key::new(1, "", 0.0, 1.0, Cluster::Alpha).size(1.5, 1.0);
        let large_size = Size::new(1484.0, 520.0);
        let small_size = Size::new(744.0, 260.0);
        let large = key_rect_with_size(&key, large_size);
        let small = key_rect_with_size(&key, small_size);

        let large_board = board_rect(large_size);
        let small_board = board_rect(small_size);
        let large_x = (large.x - large_board.x) / large_board.width;
        let small_x = (small.x - small_board.x) / small_board.width;
        assert!((large_x - small_x).abs() < 0.0001);
        assert!((large.width / large_board.width - small.width / small_board.width).abs() < 0.0001);
    }

    #[test]
    fn every_drum_pad_has_a_distinct_display_name() {
        let names: Vec<&str> = (36..=55).filter_map(drum_pad_name).collect();
        let distinct: HashSet<&str> = names.iter().copied().collect();

        assert_eq!(names.len(), 20);
        assert_eq!(distinct.len(), 20);
        assert_eq!(drum_pad_name(35), None);
        assert_eq!(drum_pad_name(56), None);
    }
}
